/**
 * 20190326@JAR:
 * 
 * 1.汉化字典'cnItems:obj',
 * 2.采集新词'cnItem:fun';
 * 
 */

//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//1.汉化字典

var cnItems = {

    _STYLE_: [
        '符号', '待归类单词', '待归类词组', '待归类长句', '成就'
    ],
    _OTHER_: [],

    //.0.符号
    '': '',
    '---': '———',
    '¯\_(ツ)_/¯': '¯\_(ツ)_/¯',

    //.待归类

    //.1.待归类单词
    'AutoBiz#0': '自动商务#0',
    'C-Levels': 'C级',
    'Caretaker': '管理人',
    'Interns': '实习生',

    //.2.待归类词组
    'A Fair Day\'s Wage': '公平日的工资',
    'A Leg Up on the Pile': '桩上的一条腿',
    'A New Sheriff In Town': '镇上的新警长',
    'A Team Player': '团队合作者',
    'Above and Beyond': '超越自我',
    'Acceptable Losses': '可接受的损失',
    'Achievement Descriptions Read': '成就说明阅读',
    'Achievements Unlocked': '成就解锁',
    'Acquisition Boost Bonus': '收购提升奖金',
    'Acquisition Time Boosted': '收购时间提升',
    'Acquisition Value Multiplier': '收购价值乘数',
    'Acquisitions Sold': '收购已售出',
    'Acquisitions Sold (All Businesses)': '收购已售出（所有业务）',
    'Acquisitions Waiting to Cash Out': '收购等待兑现',
    'All In A Day\'s Work': '所有在一天的工作',
    'All Talk and Some Action': '所有谈话和一些行动',
    'All-Encompassing System': '包罗万象的系统',
    'All-Powerful Global Conglomerate': '全能的全球企业集团',
    'All-Seeing': '到处可见',
    'Alpha and Omega': '阿尔法和欧米茄',
    'Always Been Closing': '一向被关闭',
    'Always Bullish': '总是看涨',
    'An Eye for Efficiency': '注重效率',
    'Ancient Cyclopean Construct': '古代独立建筑',
    'Angel Investor': '天使投资人',
    'Annuit Cœptis': '年报',
    'Ascendant Nurturer': '转生培养者',
    'Attentive Executive': '细心的执行',
    'Auto Mod': '自动模式',
    'Auto Sell': '自动出售',
    'Away Earnings': '离线收益',
    'Away Fired': '离线离职',
    'Away Quit': '离线时长',
    'Babylonian Brother': '巴比伦兄弟',
    'Back for More': '回到更多',
    'Bankruptcies Declared': '破产宣告',
    'Bankruptcy Multiplier': '破产乘数',
    'Barely Lifted a Finger': '勉强抬起一根手指',
    'Base Email Chance': '基础电子邮件几率',
    'Base Mod to Cash Per Second': '基础模式现金每秒',
    'Basically Lazy': '基本上懒惰',
    'Basically Too Much Clicking': '基本上太多点击了',
    'Behold Now Behemoth': '看哪，现在庞然大物',
    'Best of Breed': '最佳品种',
    'Best Regards': '最好的祝福',
    'Bewildered Herd': '迷茫的牛群',
    'Big Spender': '大富豪',
    'Big-Box Factory': '大箱工厂',
    'Big-Game Coolhunter': '大型猎酷者',
    'Bilderberger': '彼尔德伯格',
    'Bizmeth Artisan': '比斯米特工匠',
    'Bleeding Edge Visionary': '前沿有远见',
    'Bloodshot & Shaking': '充血和摇晃',
    'Blue Bloods': '贵族',
    'Blue Chip Bigwig': '蓝筹要人',
    'Blue Lives Matter': '蓝色的生活问题',
    'Blue Ocean Strategist': '蓝海战略',
    'Blue-Sky Thinker': '蓝天思考者',
    'Bonus for Time Played': '游戏时间奖励',
    'Bonus Per Achievement': '每项成就奖金',
    'Bonus Per Employee': '每个员工的奖金',
    'Bonus to Email Payout': '电子邮件支付的奖金',
    'Born Leader': '天生的领袖',
    'Bought the World a Coke': '给全世界买了一杯可乐',
    'Broken Spirit': '破碎的精神',
    'Broker of Mammon': '财神经纪人',
    'Brownian Ratcheter': '布朗·拉切特',
    'Brute Forcer': '野蛮人',
    'Business Decimator': '业务抽取器',
    'Business Omniscient': '商业无所不知',
    'But Failure is Not a Crime': '但失败不是犯罪',
    'Canceled Investments': '取消的投资',
    'Cash Earned by Clicking': '通过点击获得的现金',
    'Cash Earned During Windfalls': '在意外收获期间获得的现金',
    'Cash Earned From Acquisitions': '收购所得现金',
    'Cash Earned From Emails': '从电子邮件获得的现金',
    'Cash Earned From Expired Emails': '从过期电子邮件中获得的现金',
    'Cash Earned From Fresh Emails': '从新的电子邮件获得的现金',
    'Cash Earned From Investments': '投资赚取的现金',
    'Cash Earned From Long Investments': '长期投资赚取的现金',
    'Cash Earned From Short Investments': '短期投资赚取的现金',
    'Cash Earned From Urgent Emails': '从紧急电子邮件中获得的现金',
    'Cash Earned in Total': '总计赚的现金',
    'Cash Earned in Total (All Time)': '总计赚的现金（所有时间）',
    'Cash Earned Per Click': '每次点击赚取的现金',
    'Cash Earned Per Hour': '每小时赚取的现金',
    'Cash Earned Per Minute': '每分钟赚取的现金',
    'Cash Earned Per Second': '每秒赚取的现金',
    'Cash Earned Per Second (Minus Investments)': '每秒赚取的现金（减去投资）',
    'Cash in Hand': '手头现金',
    'Cash Spent': '现金花费',
    'Catching all the Breaks': '抓住所有休息时间',
    'Cautious': '谨慎',
    'Chain of Command': '指挥链',
    'Middle Managers': '中层管理',
    'Wage Slaves': '工资奴隶',
    'Get Back to Me by EOD': '按计划返回给我',
    'Lead Magnet': '领导引力',
    'Privatized Cops': '私有化警察',
    'Working Stiff': '劳动阶层',
    'War Profiteer': '战争利益',
    'Warrior Poet': '战士诗人',
    'Waste Manager': '废物管理',
    'We Love Our Cops': '我们爱我们的警察',
    'Wealth Begets Wealth': '财富带来财富',
    'Wearer of All Hats': '所有帽子的佩戴者',
    'Wearer of Multiple Hats': '多个帽子的佩戴者',
    'Webinar Wizard': '研讨会向导',
    'Weekend Warrior': '周末战士',
    'Well-Deserved Winnings': '当之无愧的奖金',
    'Whitepaper Wunderkind': '白皮书神童',
    'Windfall Multiplier': '暴利倍增',
    'Winners Never Quit': '胜者永不退出',
    'Withering Serf': '萎凋农奴',
    'Words Chatted': '谈天说地',
    'Wordsmith': '语言大师',
    'Work Harder, Not Smarter': '努力工作，不要太聪明',
    'Work Will Set You Free': '工作会让你自由',
    'You Clicked Too Many Times': '你点击太多次了',
    'You Have Clicked Too Much': '你已点击太多了',
    'You Have to Expedite This': '你必须加快这个',
    '0% Tax Rates': '',
    '1% Inspiration': '',
    '100% Unemployment': '',
    '168-Hour Work Weeks': '',
    '24-Hour Trading Exchanges': '',
    '4, 8, 15, 16, 23, 42': '',
    '80-Million-Pound Gorilla': '',
    '800-Pound Gorilla': '',
    '9-to-5 Lobbyists': '',
    'Contracted with America': '',
    'Convenience Fees': '',
    'Cooker of Books': '',
    'Copper Coins': '',
    'Corner Store': '',
    'Corporate Empath': '',
    'Corporate Espionage': '',
    'Corporate Indulgences': '',
    'Corporate Loyalist': '',
    'Cosmic Tycoon': '',
    'Cost-of-Living Decreases': '',
    'Country Club Lobbyists': '',
    'Cracked Coins': '',
    'Creative Accounting': '',
    'Crime Dog': '',
    'Crony Capitalist': '',
    'Crude Coins': '',
    'Cubicle Connoisseur': '',
    'Cultural Marxism': '',
    'Currency Manipulator': '',
    'Current Employees': '',
    'Current Valuation': '',
    'Cursed Monkey\'s Paw ': '',
    'Customer Courtier': '',
    'Customer Relationship Master': '',
    'Cyclonic Brainstormer': '',
    'Dabbler': '',
    'Daddy Warbucks': '',
    'Daily Lunch Pick-Up': '',
    'Day Trader': '',
    'Deadbeat Decision-Maker': '',
    'Death Squad Moneylenders': '',
    'Decentralized Crypto-Inboxes': '',
    'Decimator': '',
    'Declassified Coins': '',
    'Deep State': '',
    'Deeper Mass Graves': '',
    'Default Acquisitions Executives': '',
    'Defense Lobbyists': '',
    'Definitely Too Many': '',
    'Departmental Insolvency': '',
    'Destiny Manifested': '',
    'Destroyer of Worlds': '',
    'Detailed Spreadsheets': '',
    'Devil-Possessed Fingers': '',
    'Did you say, \'Officer,I am not resisting you ? \'': '',
    'Digital Storyteller': '',
    'Direct Lines to HR': '',
    'Dirt-Covered Coins': '',
    'Dirty Coins': '',
    'Disaster Price-Gouging': '',
    'Disaster Reliever': '',
    'Disciplinary Pay Cuts': '',
    'Disciplined Debt Collectors': '',
    'Discount For Acquisition Workers': '',
    'Discount Leads': '',
    'Disruptor': '',
    'Diverse Investments': '',
    'Diversified': '',
    'Dividend Destroyer': '',
    'Divine Mandates': '',
    'Divorce Papers': '',
    'Dollars Per Hour': '',
    'Dollars Per Minute': '',
    'Dollars Per Second': '',
    'Domino Champ': '',
    'Donated Coins': '',
    'Door-to-Door Charlatan': '',
    'Doubled Down': '',
    'Downtrodden Workhorse': '',
    'DPS Multiplier Bonus': '',
    'Draconian Brand Compliance': '',
    'Dry Powdered': '',
    'Dubious Investment Firms': '',
    'Dulled Pain Receptors': '',
    'Duration Per Windfall': '',
    'Dusty Coins': '',
    'Duty-Free': '',
    'Dynamic Problem Solver': '',
    'Dystopian Imperial Cartel': '',
    'Ear to Ear, Baby': '',
    'Earned from Research': '',
    'Earned While Away': '',
    'Earning Rate While Away': '',
    'Efficient Stratcom': '',
    'Eight Hours Rest': '',
    'Elder Statesman': '',
    'Elected Official': '',
    'Elephant Hunter': '',
    'Email Away Unlocked': '',
    'Email Benefits Transfer Card': '',
    'Email Chance Multiplier': '',
    'Email Freshness Timer': '',
    'Email Text Bonus Multiplier': '',
    'Emails Answered': '',
    'Emails Answered (All Businesses)': '',
    'Emergency Prepared': '',
    'Employee Discount': '',
    'Employee of the Month': '',
    'Employee Types Available': '',
    'Employee Types Employed': '',
    'Employee-Wide Modifier': '',
    'Employees Employed': '',
    'Employees Who Couldn\'t Hack it': '',
    'Enhanced Interrogations': '',
    'Entrenched Lobbyists': '',
    'Esoteric Monoliths': '',
    'Esprit De Corporate': '',
    'Established Corporation': '',
    'Eternal Recurrence': '',
    'Ethereal Sleeplessness': '',
    'Even More of \'Em ': '',
    'Ever Vigilant': '',
    'Every war but class war.': '',
    'Everything is a Priority': '',
    'Everything Must Go': '',
    'Everything\'s Coming Up Milhouse ': '',
    'Evil Disembodied Fingers': '',
    'Executive Assistants': '',
    'Executive Disgust': '',
    'Executive Financiers': '',
    'Executive Lobbyists': '',
    'Exhilirating Rhetoric': '',
    'Expired Emails Answered': '',
    'Exploitable Laborer': '',
    'Extensive Nerve Damage': '',
    'Extra Charisma': '',
    'Extra Email Addresses': '',
    'Extra Phones': '',
    'Extra-Broken Windows': '',
    'Extra-Judicial Killings': '',
    'Extrajudicial Prosecutors': '',
    'Extremely Fine Print': '',
    'Fabric Coins': '',
    'Faceless Multinational Corporation': '',
    'False-Flag Operations': '',
    'Falsely Conscious': '',
    'Family Photos': '',
    'Faster Software': '',
    'Faster-than-Light Growth': '',
    'Fat Cat': '',
    'Fearless Stock Brokers': '',
    'FEMA Internment Camps': '',
    'Fiercely Independent': '',
    'Filing for Chapter 50': '',
    'Financial Consultants': '',
    'Finger Exercises': '',
    'Finger on the Button': '',
    'Finger on the Pulse': '',
    'Finger-Enhancing Drugs': '',
    'Fire Sale Afficionado': '',
    'Firehose Recipient': '',
    'Firing Spree': '',
    'Firings in Name Only': '',
    'First Responder': '',
    'Flimsy Protective Railings': '',
    'Fluoridated Water': '',
    'Flush with Cash': '',
    'Focus Group Fanatic': '',
    'Folksy Servility': '',
    'For A Goddamn Percentage': '',
    'Forced HGH Injections': '',
    'Forced Thimerosal Vaccines': '',
    'Fortune Favors the Fortunate': '',
    'Founder': '',
    'Four-Dimensional Capitalist': '',
    'Free Lunches': '',
    'Free-Falling Minimum Wages': '',
    'Fresh Emails Answered': '',
    'Fresh New Startup': '',
    'Fresh Suits': '',
    'Fresh-Faced Candidate': '',
    'From Your Keyboard to God\'s Ear': '',
    'Frothier Markets': '',
    'Frozen Pensions': '',
    'Fruit-Flavored Coins': '',
    'Full Global Conquest': '',
    'Full Sea Drainage': '',
    'Full-Body Delousing': '',
    'Full-Stack': '',
    'Fully Legal Extortion': '',
    'Fully Lucid Nightmares': '',
    'Fully Primed Pumps': '',
    'Fully Qualified Leader': '',
    'Fun Boss': '',
    'Functionally Literate': '',
    'Furious Subtext': '',
    'Fuzzier Math': '',
    'G.A.O.T.U.': '',
    'Game Changer': '',
    'Gaseous Coins': '',
    'Generational Debts': '',
    'Gently-Used Ear Plugs': '',
    'Giver of 110%': '',
    'Glamorous Glennis': '',
    'Globalizer': '',
    'Gold Coins': '',
    'Golden Parachutes': '',
    'Good Neighbor': '',
    'Good Quarterly Numbers': '',
    'Government Grants': '',
    'Gratuitous Nepotism': '',
    'Gravimetric Revenue Displacement': '',
    'Greasier Elbows': '',
    'Greedy Attorneys': '',
    'Greenfield Territorialist': '',
    'Gritty Perseverance': '',
    'Growth Hacked': '',
    'Growth-Oriented': '',
    'Hands-Off': '',
    'Hands-On': '',
    'Harbinger of Trends': '',
    'Hard-Earned': '',
    'Haven\'t Heard Back...': '',
    'Haver of Bandwidth': '',
    'Hawthorne Effective': '',
    'Hear ye, the doctor has seen Nautulius.': '',
    'Highest Possible Roller': '',
    'Highest-Strung': '',
    'Hiring Spree': '',
    'Historic Institution': '',
    'Hoarder': '',
    'Hockey Stick Growth': '',
    'Homeland Eradicator of Local Militants': '',
    'Hostile Architecture': '',
    'How\'s That Boot Taste?': '',
    'Huge Chattery Teeth': '',
    'I Am the Bread of Life': '',
    'I Declare... Bankruptcy!': '',
    'I Need it Yesterday': '',
    'Idle Bonus Cash Earned': '',
    'Idle Bonus Multiplier': '',
    'Idle Bonus Rate': '',
    'If a man\'s not a success, he\'s got no one to blame but himself.': '',
    'Imperial Lord of Leads': '',
    'Imperialist Moneylenders': '',
    'Imported Coins': '',
    'In Search of Excellence': '',
    'In the Black': '',
    'In The Trenches': '',
    'In-House Accountants': '',
    'Inbox Maximum': '',
    'Incapable of Delegation': '',
    'Incomprehensible Jargon': '',
    'Incubated': '',
    'Indentured Servitude': '',
    'Independent Auditors': '',
    'Industrialist': '',
    'Infinite Self-Replication': '',
    'Infinitely Scalable': '',
    'Inheritance': '',
    'Inhuman Patience': '',
    'Initial Patent Offering': '',
    'Initial Price': '',
    'Innovator': '',
    'Insider Tips & Tricks': '',
    'Interest Rate (Per Minute)': '',
    'Intergenerational Labor': '',
    'International Monetary Fun!': '',
    'International Shell Companies': '',
    'Interpersonally Skilled': '',
    'Invasive Data-Mining': '',
    'Inverted Salaries': '',
    'Investment Boost Bonus': '',
    'Investment Time Boosted': '',
    'Investments Waiting to Cash Out': '',
    'It merely required no character.': '',
    'It\'s Got a Lot of Numbers In It': '',
    'It\'s Too Many Clicks': '',
    'Jahbulon\'s Dominion': '',
    'Jingoistic Fervor': '',
    'Jolly Green Giant': '',
    'Junta Lobbyists': '',
    'Just Catching Up': '',
    'Just Checking In...': '',
    'Just Enough Cooks': '',
    'Kicked Back': '',
    'La-li-lu-le-lo': '',
    'Landed Gentry': '',
    'Last Time Active': '',
    'Late-Night Raids': '',
    'Law-Abiding Debt Collectors': '',
    'Le Epic Bacon Genius': '',
    'Leave No Trace': '',
    'Legendary Conglomerate': '',
    'Les Enfants Terrible': '',
    'Less Bread, Fewer Roses': '',
    'Let\'s Take This Offline': '',
    'Lifer': '',
    'Lightning Reflexes': '',
    'Limited Merit Promotions': '',
    'Lingoism': '',
    'LinkedIn Luminary': '',
    'Lisan al Gaib': '',
    'Liver Failure': '',
    'Loaned Coins': '',
    'Lobbyists Abroad': '',
    'Local Establishment': '',
    'Locked Doors': '',
    'Logorrheic Professionalism': '',
    'Long Investments (1 Hour or Over)': '',
    'Long Lists of Names': '',
    'Look Upon My Works': '',
    'Loop Me In': '',
    'Looser Cannons': '',
    'Lord of the Round Table': '',
    'Loss Leader': '',
    'Lost Lemurian': '',
    'Lots of Clicking': '',
    'Lots of Clicks, Maybe Too Many': '',
    'Low-Functioning Sociopath': '',
    'Low-Hanging Fruitarian': '',
    'Low-Priced Plastic Goods': '',
    'Luck Had Nothing to Do With It': '',
    'Lucky Rabbit\'s Foot': '',
    'Lucrative Charismata': '',
    'Lumpenproletariat': '',
    'Lunch Breaker': '',
    'Lunch with the Bosses': '',
    'Lyrical Away Messages': '',
    'Make Total Employ': '',
    'Making Some Big Changes': '',
    'Malthusian Trapper': '',
    'Man-Made Lakes of Cash': '',
    'Mandatory Engagement': '',
    'Mandeville Pointed': '',
    'Manual Click Multiplier': '',
    'Manual Click Percentage': '',
    'Manual Clicks': '',
    'Manual Clicks (All Time)': '',
    'Market Cannibal': '',
    'Market Diviner': '',
    'Market Penetrator': '',
    'Masonic Lobbyists': '',
    'Mass Gun Confiscation': '',
    'Mass Incarceration': '',
    'Massive Layoffs': '',
    'Massive Layoffs Conducted (All Businesses)': '',
    'Massive Subsidies': '',
    'Master Delegator': '',
    'Master of Margins': '',
    'Master of the Pipeline': '',
    'Maverick': '',
    'Maximization of Throughput': '',
    'Maximized Leverager': '',
    'Maybe Too Many Now': '',
    'Means-Tested Paychecks': '',
    'Menacing Word Choice': '',
    'Mercenary Groups': '',
    'Meritocrat': '',
    'Micromanager': '',
    'Midnight Oil': '',
    'Militarized Checkpoints': '',
    'Militarized Lobbyists': '',
    'Militarized Market Surveyor': '',
    'Militarized Riot Control': '',
    'Military Defense Attorneys ': '',
    'Military-Issue Coins': '',
    'Minimally Viable': '',
    'Minimum Email Value': '',
    'Minimum Viable Personnel': '',
    'Missing Coins': '',
    'Mission Accomplished': '',
    'Mission Civilisatrice': '',
    'Mission Critical': '',
    'MKUltra Sleeper Agents': '',
    'Moderate Lobbyists': '',
    'Modifier': '',
    'Monetized': '',
    'Monopolized Industries': '',
    'Monstrous Work Ethic': '',
    'More Brow Sweat': '',
    'More gods, more masters.': '',
    'More Hard Drives': '',
    'More of an Ideas Person': '',
    'More Vision': '',
    'Most Valuable Patent': '',
    'Motivational Speeches': '',
    'Motivational Work Conditions': '',
    'Moving Fast & Breaking Everything': '',
    'Mud-Caked Coins': '',
    'Multinational Moneylenders': '',
    'Must Have Missed a Decimal Point': '',
    'My Name is My Name': '',
    'Mysterious Fingers': '',
    'Naive Resilience': '',
    'Name Tags': '',
    'Negative Severance': '',
    'Neo-Feudal Lord': '',
    'Net Value': '',
    'New Achievements': '',
    'New Policies': '',
    'New Upgrades': '',
    'New World Order': '',
    'Next Bankruptcy Multiplier': '',
    'No Limits to Growth': '',
    'No Rush': '',
    'No-Bid Contracts': '',
    'Non-Competes': '',
    'Non-Stop Jackpot Winner': '',
    'None More Bankrupt': '',
    'Not Here To Make Friends': '',
    'Nothing but Aces': '',
    'Nothing on the Inside': '',
    'Novikovian Time Manipulation': '',
    'Novus Ordo Seclorum': '',
    'Now, Hold On, Mr. Potter': '',
    'Now, we can see a new world coming into view.': '',
    'Number Fudgings Occurred (All Businesses)': '',
    'Nutmeg is not the question.': '',
    'Occult Gatherings': '',
    'Odious Debt Collectors': '',
    'Off-Shore Accountant': '',
    'Off-Site Data Centers': '',
    'Office Drone': '',
    'Officer Friendly': '',
    'Oily Coins': '',
    'Old Money': '',
    'Old Moneybags': '',
    'Omnidimensional Marketing': '',
    'On A Roll': '',
    'On Call': '',
    'On the Ball': '',
    'Once when I was a child, I almost drowned. It\'s just like that feeling.': '',
    'One Man Army': '',
    'One World Unity Army': '',
    'One-World Globalist': '',
    'Open Borders': '',
    'Operation Rolling Layoffs': '',
    'OSHA Doesn\'t Need to Know': '',
    'Otherwordly Rituals': '',
    'Out-of-Town Scabs': '',
    'Outgoing Emails Sent (All Businesses)': '',
    'Outright Lies': '',
    'Overall Time Boosted (All Businesses)': '',
    'Overcooked Books': '',
    'Overnight Conferences': '',
    'Paid Protestors': '',
    'Paradigm Shifter': '',
    'Paramilitary Debt Collectors': '',
    'Passive Observer': '',
    'Patents Sold (All Businesses)': '',
    'Paternalistic Guilt': '',
    'Patriot Lobbyists': '',
    'Peacekeeper': '',
    'Peak Efficiency': '',
    'Penny Stock Pro': '',
    'Permanent Isolation Cubicles': '',
    'Perpetual Motion Machine': '',
    'Personal Assistants': '',
    'Personal Responsibility': '',
    'Personal Touches': '',
    'Personnel Realignment Specialists': '',
    'Petrol-Soaked Coins': '',
    'Piggy Banker': '',
    'Pinker Slips': '',
    'Pinkerton Reinforcements': '',
    'Pipeline Prophet': '',
    'Playful Threats': '',
    'Playing the Long Game': '',
    'Please Advise': '',
    'Please Answer, Please': '',
    'Please Respond ASAP': '',
    'Plenty to Go Around': '',
    'Plutocrat': '',
    'Pocket Politicians': '',
    'Poisonous Coins': '',
    'Police Union Attorneys': '',
    'Police Union Lobbyists': '',
    'Policies Accepted (All Businesses)': '',
    'Policy Away Unlocked': '',
    'Political Executions': '',
    'Postcards Home': '',
    'Powder-Blackened Coins': '',
    'Predatory Pricing': '',
    'Premature': '',
    'Presidential Lawyers': '',
    'Preternatually Wealthy': '',
    'Pretty Much All of \'Em': '',
    'Pretty Much Just Lucky': '',
    'Preventative Dental Extraction': '',
    'Price': '',
    'Prime Deliverable': '',
    'Primordial Global Conspiracy': '',
    'Prison Lobbyists': '',
    'Privatized Tax Collection': '',
    'Privileged': '',
    'Proactive Leadership': '',
    'Procrastinator': '',
    'Productivity Mutations': '',
    'Professional Liquidator': '',
    'Professional Lobbyists': '',
    'Prolific Writer': '',
    'Prompt Responder': '',
    'Propaganda Machines': '',
    'Protestant Work Ethic': '',
    'Public Defenders': '',
    'Public Shaming': '',
    'Pumping and Dumping': '',
    'Puppetmasters': '',
    'Purge of the Weak': '',
    'Putting Out Fires': '',
    'Q. And Babies? A. And Babies.': '',
    'Quantity': '',
    'Quantity Modifier': '',
    'Quantum Computers': '',
    'Quick Question...': '',
    'Quickest Draw': '',
    'Quincentennial Celebration': '',
    'Quitters Never Win': '',
    'R&D Time Boosted': '',
    'Radioactive Coins': '',
    'Rail Spike Coins': '',
    'Ramen Profitable': '',
    'Randian Hero': '',
    'Rapid Fire Speculator': '',
    'Rapid Ideation': '',
    'Rapid Innovation': '',
    'Rapidly Pivoting': '',
    'Reaching Out': '',
    'Real Artists Ship': '',
    'Realignment of Growth Opportunities': '',
    'Rearden Metallic': '',
    'Reasonably Suspicious': '',
    'Reassuring Leadership': '',
    'Reduced Bonuses': '',
    'Regular Emails': '',
    'Reinforced Bank Vaults': '',
    'Relentless Momentum': '',
    'Relentless Rationalization': '',
    'Repurposed Coins': '',
    'Research Boost Bonus': '',
    'Reshaper of Worlds': '',
    'Resource Extraction': '',
    'Restless Defender': '',
    'Reverse Universal Heat Death': '',
    'Reverse Vacation Accrual': '',
    'Right-Wing Guerillas': '',
    'Righteous Debt Collectors': '',
    'Rightsizing!': '',
    'Risk of Death': '',
    'Risk Reduction': '',
    'Robber Baron': '',
    'Rockstar': '',
    'Roving Death Squads': '',
    'Rugged Individualism': '',
    'Running Fat': '',
    'Ruthless Streamliner': '',
    'Sacks with Dollar Signs': '',
    'Sadistic Debt Collectors': '',
    'Salaryman': '',
    'Sales Hotshots': '',
    'Salted Coins': '',
    'Save File Size': '',
    'Scalper': '',
    'Scorched Earth Policies': '',
    'Screaming into the Void': '',
    'Screaming Sessions': '',
    'Secret Coins': '',
    'Secret Handshakes': '',
    'Seed Accelerated': '',
    'Seed Money': '',
    'Self-Made Millionaire': '',
    'Self-Motivation': '',
    'Self-starter': '',
    'Sell Value': '',
    'Semi-Deified Tribute': '',
    'Semi-Qualified Stock Brokers': '',
    'Senior Lobbyists': '',
    'Serial Entrepeneur': '',
    'Set It and Forget It': '',
    'Seven-Leaf Clover': '',
    'Seven-Million-Leaf Clover': '',
    'Several People Are Typing': '',
    'Shadow Governments': '',
    'Shop Talk': '',
    'Short Investment Bonus': '',
    'Short Investments (Under 1 Hour)': '',
    'Shortened Vacations': '',
    'Shorter Selling': '',
    'Sick and Tired of Winning': '',
    'Sick Capital Gains': '',
    'Silver Coins': '',
    'Simultaneous Acquisitions Allowed': '',
    'Simultaneous Investments Allowed': '',
    'Sincere Condolences': '',
    'Sisyphean Perseverance': '',
    'Slanderous Accusations': '',
    'Slick Cowboy Stock Brokers': '',
    'Slurry-Stained Coins': '',
    'Smaller Cubicles': '',
    'Smart Words Replied': '',
    'Snake Oil Sweet-Talker': '',
    'Social Butterfly': '',
    'Some of Each': '',
    'Soot-Covered Coins': '',
    'Sorry for the Delayed Response': '',
    'Spam Disposal': '',
    'Special Forces Philosophy': '',
    'Speed Bonus': '',
    'Speed Boost': '',
    'Sprawling Industrial Wasteland': '',
    'Stabs Tab Views': '',
    'Staring Dead-Eyed at the Inbox': '',
    'Start Time (All Businesses)': '',
    'Start Time (This Business)': '',
    'Sticky Coins': '',
    'Stirring Corporate Pride': '',
    'Stress Level': '',
    'Stress Reduced Manually': '',
    'Stress Reduction Bonus': '',
    'Stress Reduction Multiplier': '',
    'Strike Gold': '',
    'Strip-Mall Moneylenders': '',
    'Stronger Brand Identity': '',
    'Structural Adjustment Programs': '',
    'Struggling Insomniac': '',
    'Struggling Sadsack': '',
    'Student Lobbyists': '',
    'Student Protest Crackdowns': '',
    'Stuffy Office Lobbyists': '',
    'Sub-Prime Leader': '',
    'Successful Investments': '',
    'Successful Investments (All Businesses)': '',
    'Sugary Coins': '',
    'Suicide Nets': '',
    'Superliminal Advertising': '',
    'Superluminal Thinker': '',
    'Supernatural Magnate': '',
    'Supernatural Stock Brokers': '',
    'Supplemental Email Assistance Program': '',
    'Supplied & Demanded': '',
    'Supranational Currency': '',
    'Surge Pricing': '',
    'Surveillance Capitalist': '',
    'Sweat Shops': '',
    'Sweatier Equity': '',
    'Synergy-Related Adjustments': '',
    'Systematic Downsizing': '',
    'Tactical Flanking': '',
    'Tactical Trading': '',
    'Talk the Talk': '',
    'Targeted Drone Firing': '',
    'Targeted Surveillance': '',
    'Targeted Tax Cuts': '',
    'Team-Building Exercises': '',
    'Telephone Terrorist': '',
    'Temporarily Embarrassed Millionaires': '',
    'Tense & Silent Meetings': '',
    'Teracorn': '',
    'Terminal Income Velocity': '',
    'Textile Coins': '',
    'Thanks in Advance': '',
    'The .0001%': '',
    'The 0.0000001%': '',
    'The 1%': '',
    'The Absence of Alternatives': '',
    'The Affordable Emails Act': '',
    'The Ambitious Sales Model': '',
    'The Art of Acquisition': '',
    'The Bosses': '',
    'The Challenger Sales Model': '',
    'The Chosen One': '',
    'The Daemon Awakens': '',
    'The Death Special': '',
    'The Desire to Achieve': '',
    'The Divine Right of Sales': '',
    'The Elite Legal Team': '',
    'The Empire of Liberty': '',
    'The Eye of Market Providence': '',
    'The Fifth Column': '',
    'The Five Commas Club': '',
    'The Fourth Woe': '',
    'The Freddie Mac Award for Ethics': '',
    'The Ghosts of Fallen Businesses': '',
    'The Giant Void': '',
    'The Great Communicator': '',
    'The Great Motivator': '',
    'The Holy Finger': '',
    'The Idle Class': '',
    'The Imperial Cult of the Goat': '',
    'The Inbox of the Covenant': '',
    'The Keynesian Dream': '',
    'The Last Best Hope of Earth': '',
    'The Leanest Methodology': '',
    'The Lidless Eye': '',
    'The Little Red Book of Acquiring': '',
    'The Man Behind the Curtain': '',
    'The Man Who Thought Different': '',
    'The Mark of the Beast': '',
    'The Means of Production': '',
    'The Militant Sales Model': '',
    'The Monopoly on Violence': '',
    'The Most Private of Equity': '',
    'The Mostly Invisible Hand': '',
    'The Name on the Door': '',
    'The Occult Sales Model': '',
    'The Odic Sales Force': '',
    'The Office Gossip': '',
    'The Oligarchs': '',
    'The People\'s Stick': '',
    'The Personable Sales Model': '',
    'The Poincaré Bankruptcy Theorem': '',
    'The Primordial Baʿal': '',
    'The Promise of Death': '',
    'The Protectors of Our Industries': '',
    'The Reasonable Sales Model': '',
    'The Reckless Sales Model': '',
    'The Roarkian Ideal': '',
    'The Ruling Class': '',
    'The Second Estate': '',
    'The Seven Commas Club': '',
    'The Shoulders of Atlas': '',
    'The Spectre of Reorg': '',
    'The Spoils of War': '',
    'The Stargate Sales Model': '',
    'The Sum Total of the Universe': '',
    'The Supreme Sales Model': '',
    'The Surplus Valuable': '',
    'The Telecom Cowboy': '',
    'The Three Commas Club': '',
    'The Wild Black Yonder ': '',
    'The World Banker': '',
    'They have nothing to lose but their chains.': '',
    'Thin Blue Line': '',
    'Thinly-Veiled Harassment': '',
    'This is a Business': '',
    'This Time, It\'s Personnel': '',
    'Thought Leader': '',
    'Threatening Diction': '',
    'Time Bonus Rate (Hourly)': '',
    'Time Dedicated to Investments': '',
    'Time Dedicated to Investments (All Businesses)': '',
    'Time Earning While Away': '',
    'Time Spent Idle': '',
    'Time Spent Idle (All Businesses)': '',
    'Time-Release Coins': '',
    'Timeless Secret Cabal': '',
    'Timesheet Authoritarianism': '',
    'Titan of Industry': '',
    'Tobashi Schemer': '',
    'Too Big to Fail': '',
    'Top of a Better Funnel': '',
    'Total Financial Ouroboros': '',
    'Total Mod to Cash Per Second': '',
    'Total Organizational Streamlining': '',
    'Total Storage': '',
    'Total Windfalls': '',
    'Total Windfalls (All Businesses)': '',
    'Touching Base': '',
    'Transparent Corruption': '',
    'Trend Predestination': '',
    'Trickle-Down Economics': '',
    'trigger': '',
    'Trilateral Commissioner': '',
    'Trimming the Fat': '',
    'Trojan Horse Keyloggers': '',
    'True Believer': '',
    'Two-Day Weekend': '',
    'Ubermensch': '',
    'Ultra-Regressive Taxation': '',
    'Unachievable Metrics': '',
    'Under New Management': '',
    'Undocumented Coins': '',
    'Unearned Self-Confidence': '',
    'Unicorn': '',
    'Universal Acquisition': '',
    'Universal Acquittal': '',
    'Universal Basic Email': '',
    'Universal Cash Bail': '',
    'Universal Flux': '',
    'Unlimited Vacation Days': '',
    'Unpaid Assistant': '',
    'Unspeakable Lobbyists': '',
    'Unstoppable Terrifying Luck': '',
    'Untaxed Coins': '',
    'Until the End of Time': '',
    'Upgrades Owned': '',
    'Upgrades/Achievements Tab Views': '',
    'Upper-Class Twit': '',
    'Upper-Level Lobbyists': '',
    'Urgent Email Bonus': '',
    'Urgent Emails': '',
    'Urgent Emails Answered': '',
    'Urgent Emails Answered (All Businesses)': '',
    'Useless Degrees': '',
    'User Storyteller': '',
    'Value': '',
    'Value Bonus': '',
    'Value Boost': '',
    'Value Mod': '',
    'Variable Capitalizer': '',
    'Vast Real Estate Acquisitions': '',
    'Venture Capital': '',
    'Venture Capitalist': '',
    'Version': '',
    'Very Free Markets': '',
    'Very Polite': '',
    'Very Rude': '',
    'Vicious Litigation': '',
    'Vigilant Prodder': '',
    'Virulent Feminism': '',
    'Volunteer Lobbyists': '',
    'Voter Suppression': '',
    'Water-Logged Coins': '',
    'Wealthy Patrons': '',
    'Well-Chopped Stocks': '',
    'Western Values': '',
    'White Coins': '',
    'White Shoes': '',
    'Whiter Phosphorous': '',
    'Why We Fire': '',
    'Yacht Lobbyists': '',


    //.3.待归类长句
    'A million dollars isn\'t cool. You know what\'s cool? A billion dollars.': '一百万美元并不酷。你知道什么才是酷吗？ 十亿美元。',
    'And So It Goes...': '如此这般……',
    'Any Update Here?': '有什么更新？',
    'Are You Getting These?': '你收到了吗？',
    'Benny, Bring Me Everyone': '本尼，给我带来每个人',
    'Can I Speak to the Manager?': '我可以和经理谈谈吗？',
    'Who Cares?': '谁在乎？',
    '<p>The ambitious <b>Middle Manager</b> is loyal to your business, striving each day to dominate your lower employees, lest they wither from a lack of motivating leadership.</p><p>Good old-fashioned common sense is their bread and butter, and they always know when it\'s time to tighten belts, roll up sleeves, and do less with more.</p>': '',
    '<p>The brave <b>Privatized Cop</b> is the defender of your business, decked out in riot gear and gas masks as the last line of defense between bricks and your windows.</p><p>Armed and ready to protect and serve, they patrol your employees\' neighborhoods, upholding a fraternal code of ethics that ensures they only open fire when unnerved.</p>': '',
    '<p>The burgeoning <b>Client State</b> provides the life-blood of your business, supplying labor and resources at prices your own borders could never match.</p><p>There may be death squads in power, but that\'s the price you have to pay for a business-friendly environment that doesn\'t frown upon the execution of political agitators</p>': '',
    '<p>The confident <b>Sales Hotshot</b> is the engine of your business, bringing your valuable product(s) to your cash-laden customer(s), whether they want them or not.</p><p>Knee-deep in the pipeline and eyes locked on the quarterly numbers, they know that your business is dog-eat-dog, and dogs just don\'t live that long.</p>': '',
    '<p>The dignified <b>Pocket Politician</b> allows your business to thrive unburdened by Byzantine regulations, which would otherwise choke the life from it like a clumsy child in a textile mill.</p><p>Moderate and charismatic, they work hard for their constituents, ensuring with every vote that the most basic of needs is met: regular GDP growth.</p>': '',
    '<p>The humble <b>Intern</b> forms the backbone of any savvy business, paid in experience and eager to please as they pad their resumes in hopes of a better tomorrow.</p><p>With the exploitable pliability of youth glistening in their eyes, they scurry through the hallowed halls of your business, wearing multiple hats and incurring minimal expenses.</p>': '',
    '<p>The mysterious <b>Shadow Government</b> is the secret benefactor of your business, encouraging social discord and diminishing cultures as they please.</p><p>While not all believe they exist, true leaders such as yourself know that a once-great populace disarmed and hamstrung by political correctness is ripe for exploitation.</p>': '',
    '<p>The noble <b>Blue Blood</b> is the soul of your business, investing in your continued growth, filling your boardrooms, and concentrating the wealth you create.</p><p>Self-made and determined, they watch for your ticker symbol as the markets climb, a sense of benevolent pride pouring over them as the dividends trickle down.</p>': '',
    '<p>The omniscient <b>Puppetmaster</b> is the primordial lizard-brain of your business, unspeakably powerful, hailing from a time beyond memory.</p><p>They may look and sound like any of us, but they travel in elite circles: tycoons and magnates, dignitaries and politicians, all gathered in hoods and masks to perform unspeakable horrors in the hidden basements of pizza parlors.</p>': '',
    '<p>The solemn <b>Wage Slave</b> is essential to the success of any growing business, dedicated to their work and trapped in an unbreakable cycle of poverty and obligation.</p><p>Through long nights and lonely weekends, they drag their ragged claws through offices and factory floors, each day hoping to be blessed with a coveted merit increase.</p>': '',
    '<p>The valorous <b>Mercenary Group</b> protects the interests of your business abroad, burning villages and salting the earth anywhere a government begins to lean left.</p><p>Stalwart and ready to just follow orders, they move from city to city, drone\'s-eye-view overhead, guns trained on the nearest target as they wait for the order to liberate.</p>': '',
    '<p>The wise <b>C-Level</b> is the conductor of your business, always thinking of innovative and inspiring ways to appear to meet shareholder expectations or inflate valuations.</p><p>With a keen eye and a strict sense of discipline, they approach each new day as a chance to trim the fat and bring value to their investors.</p>': '',




    //1.2.成就
    'A City Upon a Hill': '山巅之城',
    'A Clear-Eyed Realist': '慧眼智者',
    'A Deal with the Devil': '与魔共舞',
    'A Few Extra Fingers': '额外控制',
    'A Shining Trapezohedron': '闪亮梯形',
    'A Silver Spoon': '银色茶匙',
    'Absentee Landlordism': '采邑领主',
    'Additional Buses': '附赠公交',
    'Administrative Dirty-Work': '政治黑幕',
    'Aerospace Tech Group': '航天科工',
    'Aggressive Debt Collection': '债务追索',
    'Aggressive Debt Collectors': '专业追债',
    'All Accounts Deleted': '清除账户',
    'All-White Juries': '公平审判',
    'Amateur Debt Collectors': '业余追债',
    'Ambulance Chasers': '紧急救助',
    'Ancient Lobbyists': '古风说客',
    'Anthracite Coins': '亮煤货币',
    'Anti-Homeless Measures': '安民措施',
    'Anti-Union Literature': '革命手册',
    'Anxiety Medication': '焦虑药物',
    'Arbitrary Finger-Pointing': '唯心指示',
    'Armed Militia Conscription': '兵役法案',
    'Armed Rebel Groups': '武装叛军',
    'Army Surplus Gear': '备用军资',
    'Aspirational Loyalty': '忠诚伟志',
    'Attack Ads': '抨击广告',
    'Attorneys on Retainer': '授信讼师',
    'Automated Firing Algorithms': '自动枪火',
    'Banana Coins': '香蕉货币',
    'Bane Capital': '灰色资本',
    'Baphometic Hypnotism': '宗教催眠',
    'Base Earnings': '基础收入',
    'Baseless Optimism': '盲目乐观',
    'Bathroom Panopticon': '单间浴室',
    'Bihourly Safety Meetings': '定期会晤',
    'Black Helicopters': '直升战机',
    'Black Site Debt Collectors': '黑市追债',
    'Blackened Coins': '敦化货币',
    'Blood-Speckled Coins': '血斑货币',
    'Blood-Stained Coins': '血污货币',
    'Boardroom Lobbyists': '私房说客',
    'Bomb-Scorched Coins': '弹焦货币',
    'Bootstraps': '自力更生',
    'Borrowed Coins': '虚拟货币',
    'Bottle-Cap Coins': '瓶盖货币',
    'Boundless Advertising': '无边广告',
    'Boy\'s Club Comraderie': '光腚友情',
    'Brazen & Reckless Fraud': '无耻欺诈',
    'Budget Reductions': '削减预算',
    'Bullet-Riddled Coins': '弹孔货币',
    'Bullpen Lobbyists': '社交说客',
    'Bureaucratic Law Clerks': '官僚书记',
    'Bureaucratic Moneylenders': '官商代理',
    'Burnt Coins': '燃烧货币',
    'Business Cards': '商业名片',
    'Business Precognition': '商业预感',
    'Campaign Contributions': '竞选献金',
    'Cash Bail Moneylenders': '保释代理',
    'Casual Fridays': '周五便装',
    'Casual Wage Discrimination': '薪资歧视',
    'Casus Belli': '宣战理由',
    'Catastrophic Bailouts': '灾难救援',
    'Catastrophic Health Plans': '救灾组织',
    'Centenarian Retirement': '百岁退休',
    'Chalky Coins': '白垩货币',
    'Champion of the Process': '工艺大师',
    'Chance of Windfall': '意外收获',
    'Chance to Receive Urgent Emails': '提示机会',
    'Change Agent': '更换代理',
    'Chasing Returns': '追踪回报',
    'Chat Away Unlocked': '封锁回音',
    'Chat Messages': '聊天信息',
    'Chats Completed (All Businesses)': '协商完成',
    'Cheap Hack Lawyers': '黑客律师',
    'Chem Trails': '化学痕迹',
    'Chemical-Burned Coins': '化工货币',
    'Chocolate Coins': '可可货币',
    'Choke Their Rivers With Our Bankruptcies': '破产策略',
    'Churning Out Innovation': '刺激创新',
    'CIA-Sponsored Coups': '煽动政变',
    'Circle Back': '圆滑回转',
    'Clearer Expectations': '明朗期待',
    'Click Mod': '点击模块',
    'Clicks': '批量点击',
    'Client States': '客户形态',
    'Closed-Door Meetings': '封闭会议',
    'Coal-Dusted Coins': '煤尘货币',
    'Collateral Damage': '抵押损失',
    'Colonial Hegemony': '殖民霸权',
    'Colonial Sovereignty': '殖民主权',
    'Committed Crapshooter': '完整洗脑',
    'Community Policing': '社区保安',
    'Company Cultural Hegemony': '公司洗脑',
    'Company Man': '公司成员',
    'Company Scrip': '公司票据',
    'Complete Deregulation': '完成释放',
    'Completionist': '完美主义',
    'Complimentary Amphetamines': '免费药品',
    'Comprehensive Outsourcing': '综合外包',
    'Compulsory Sedation': '强制镇静',
    'Congenial Encouragement': '正面鼓励',
    'Content Creator': '原创作者',

    _SHOWN_: function () {
        console.log(this._OTHER_);
        let
            $cni /*词汇数组*/ = arguments[0] || this._OTHER_,
            $str /*词汇字串*/ = document.createElement('div');
        $str = '汉化-待译（阳光汉化组）：\n\n';
        //整理元素
        for (let i = 0; i < $cni.length; i++) {
            $str += ('/*' + i + '*/ "' + $cni[i] + '": "",\n');
        }
        $str += '\n\n刷新可继续游戏；愿支持汉化请联系QQ：505397145。';
        alert($str);
    },

};

//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//2.采集新词

var cnItem = function () {

    //.1.传参是否非空字串
    if (!arguments[0]) return;

    //.2.检验传参是否对象
    let text = arguments[0],
        s = '';
    if (typeof (text) != "string")
        return text;
    else
        s = arguments[0].charCodeAt();

    //.3.检验传参是否英文
    if (
        s < 'A' || (s > 'Z' && s < 'a') || (s > 'z')

    ) return text;

    //.4.检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //.5.遍历尝试匹配
    for (let i in cnItems) {
        //.5.1.字典已有词汇或译文、且译文不为空，则返回译文
        if (
            text == i || text == cnItems[i] &&
            cnItems[i] != ''
        )
            return cnItems[i];
    }

    //.6.遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //.6.1.已收录则直接返回
        if (text == cnItems._OTHER_[i])
            return text;
    }

    //.7.未收录则保存
    cnItems._OTHER_.push(text);
    cnItems._OTHER_.sort(
        function (a, b) {
            return a.localeCompare(b)
        }
    );

    /*
        //开启生词打印
        //console.log(
            '有需要汉化的英文：', text
        );
    */

    //.8.返回生词字串
    return text;
};
