/**
 * 20190326@JAR:
 * 
 * 1.汉化字典'cnItems:obj',
 * 2.采集新词'cnItem:fun';
 * 
 */

//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//1.汉化字典

var cnItems = {

    _STYLE_: [
        '符号', '待归类单词', '待归类词组', '待归类长句', '成就'
    ],
    _OTHER_: [],

    //.0.符号
    '': '',
    '---': '———',
    '¯\_(ツ)_/¯': '¯\_(ツ)_/¯',
    '1111':'1111',

    //.待归类

    //.1.待归类单词
    'AutoBiz#0': '自动商务#0',
    'C-Levels': 'C级',
    'Caretaker': '管理人',
    'Interns': '实习生',

    //.2.待归类词组
    'A Fair Day\'s Wage': '公平日的工资',
    'A Leg Up on the Pile': '桩上的一条腿',
    'A New Sheriff In Town': '镇上的新警长',
    'A Team Player': '团队合作者',
    'Above and Beyond': '超越自我',
    'Acceptable Losses': '可接受的损失',
    'Achievement Descriptions Read': '成就说明阅读',
    'Achievements Unlocked': '成就解锁',
    'Acquisition Boost Bonus': '收购提升奖金',
    'Acquisition Time Boosted': '收购时间提升',
    'Acquisition Value Multiplier': '收购价值乘数',
    'Acquisitions Sold': '收购已售出',
    'Acquisitions Sold (All Businesses)': '收购已售出（所有业务）',
    'Acquisitions Waiting to Cash Out': '收购等待兑现',
    'All In A Day\'s Work': '所有在一天的工作',
    'All Talk and Some Action': '所有谈话和一些行动',
    'All-Encompassing System': '包罗万象的系统',
    'All-Powerful Global Conglomerate': '全能的全球企业集团',
    'All-Seeing': '到处可见',
    'Alpha and Omega': '阿尔法和欧米茄',
    'Always Been Closing': '一向被关闭',
    'Always Bullish': '总是看涨',
    'An Eye for Efficiency': '注重效率',
    'Ancient Cyclopean Construct': '古代独立建筑',
    'Angel Investor': '天使投资人',
    'Annuit Cœptis': '年报',
    'Ascendant Nurturer': '转生培养者',
    'Attentive Executive': '细心的执行',
    'Auto Mod': '自动模式',
    'Auto Sell': '自动出售',
    'Away Earnings': '离线收益',
    'Away Fired': '离线离职',
    'Away Quit': '离线时长',
    'Babylonian Brother': '巴比伦兄弟',
    'Back for More': '回到更多',
    'Bankruptcies Declared': '破产宣告',
    'Bankruptcy Multiplier': '破产乘数',
    'Barely Lifted a Finger': '勉强抬起一根手指',
    'Base Email Chance': '基础电子邮件几率',
    'Base Mod to Cash Per Second': '基础模式现金每秒',
    'Basically Lazy': '基本上懒惰',
    'Basically Too Much Clicking': '基本上太多点击了',
    'Behold Now Behemoth': '看哪，现在庞然大物',
    'Best of Breed': '最佳品种',
    'Best Regards': '最好的祝福',
    'Bewildered Herd': '迷茫的牛群',
    'Big Spender': '大富豪',
    'Big-Box Factory': '大箱工厂',
    'Big-Game Coolhunter': '大型猎酷者',
    'Bilderberger': '彼尔德伯格',
    'Bizmeth Artisan': '比斯米特工匠',
    'Bleeding Edge Visionary': '前沿有远见',
    'Bloodshot & Shaking': '充血和摇晃',
    'Blue Bloods': '贵族',
    'Blue Chip Bigwig': '蓝筹要人',
    'Blue Lives Matter': '蓝色的生活问题',
    'Blue Ocean Strategist': '蓝海战略',
    'Blue-Sky Thinker': '蓝天思考者',
    'Bonus for Time Played': '游戏时间奖励',
    'Bonus Per Achievement': '每项成就奖金',
    'Bonus Per Employee': '每个员工的奖金',
    'Bonus to Email Payout': '电子邮件支付的奖金',
    'Born Leader': '天生的领袖',
    'Bought the World a Coke': '给全世界买了一杯可乐',
    'Broken Spirit': '破碎的精神',
    'Broker of Mammon': '财神经纪人',
    'Brownian Ratcheter': '布朗·拉切特',
    'Brute Forcer': '野蛮人',
    'Business Decimator': '业务抽取器',
    'Business Omniscient': '商业无所不知',
    'But Failure is Not a Crime': '但失败不是犯罪',
    'Canceled Investments': '取消的投资',
    'Cash Earned by Clicking': '通过点击获得的现金',
    'Cash Earned During Windfalls': '在意外收获期间获得的现金',
    'Cash Earned From Acquisitions': '收购所得现金',
    'Cash Earned From Emails': '从电子邮件获得的现金',
    'Cash Earned From Expired Emails': '从过期电子邮件中获得的现金',
    'Cash Earned From Fresh Emails': '从新的电子邮件获得的现金',
    'Cash Earned From Investments': '投资赚取的现金',
    'Cash Earned From Long Investments': '长期投资赚取的现金',
    'Cash Earned From Short Investments': '短期投资赚取的现金',
    'Cash Earned From Urgent Emails': '从紧急电子邮件中获得的现金',
    'Cash Earned in Total': '总计赚的现金',
    'Cash Earned in Total (All Time)': '总计赚的现金（所有时间）',
    'Cash Earned Per Click': '每次点击赚取的现金',
    'Cash Earned Per Hour': '每小时赚取的现金',
    'Cash Earned Per Minute': '每分钟赚取的现金',
    'Cash Earned Per Second': '每秒赚取的现金',
    'Cash Earned Per Second (Minus Investments)': '每秒赚取的现金（减去投资）',
    'Cash in Hand': '手头现金',
    'Cash Spent': '现金花费',
    'Catching all the Breaks': '抓住所有休息时间',
    'Cautious': '谨慎',
    'Chain of Command': '指挥链',
    'Middle Managers': '中层管理',
    'Wage Slaves': '工资奴隶',
    'Get Back to Me by EOD': '按计划返回给我',
    'Lead Magnet': '领导引力',
    'Privatized Cops': '私有化警察',
    'Working Stiff': '劳动阶层',
    'War Profiteer': '战争利益',
    'Warrior Poet': '战士诗人',
    'Waste Manager': '废物管理',
    'We Love Our Cops': '我们爱我们的警察',
    'Wealth Begets Wealth': '财富带来财富',
    'Wearer of All Hats': '所有帽子的佩戴者',
    'Wearer of Multiple Hats': '多个帽子的佩戴者',
    'Webinar Wizard': '研讨会向导',
    'Weekend Warrior': '周末战士',
    'Well-Deserved Winnings': '当之无愧的奖金',
    'Whitepaper Wunderkind': '白皮书神童',
    'Windfall Multiplier': '暴利倍增',
    'Winners Never Quit': '胜者永不退出',
    'Withering Serf': '萎凋农奴',
    'Words Chatted': '谈天说地',
    'Wordsmith': '语言大师',
    'Work Harder, Not Smarter': '努力工作，不要太聪明',
    'Work Will Set You Free': '工作会让你自由',
    'You Clicked Too Many Times': '你点击太多次了',
    'You Have Clicked Too Much': '你已点击太多了',
    'You Have to Expedite This': '你必须加快这个',



    "0% Tax Rates": "0%税率",
    "1% Inspiration": "1%灵感",
    "100% Unemployment": "100%失业率",
    "168-Hour Work Weeks": "168小时工作周",
    "24-Hour Trading Exchanges": "24小时交易交易所",
    "4, 8, 15, 16, 23, 42": "4、8、15、16、23、42(数列)",
    "80-Million-Pound Gorilla": "8000万磅大猩猩",
    "800-Pound Gorilla": "800磅大猩猩",
    "9-to-5 Lobbyists": "朝九晚五的说客",
    "Contracted with America": "与美国签约",
    "Convenience Fees": "便利费",
    "Cooker of Books": "书灶",
    "Copper Coins": "铜币",
    "Corner Store": "街角店",
    "Corporate Empath": "企业移情",
    "Corporate Espionage": "公司间谍活动",
    "Corporate Indulgences": "公司放纵",
    "Corporate Loyalist": "企业忠诚者",
    "Cosmic Tycoon": "宇宙大亨",
    "Cost-of-Living Decreases": "生活成本下降",
    "Country Club Lobbyists": "乡村俱乐部说客",
    "Cracked Coins": "碎硬币",
    "Creative Accounting": "创造性会计",
    "Crime Dog": "犯罪犬",
    "Crony Capitalist": "亲信资本家",
    "Crude Coins": "粗钱币",
    "Cubicle Connoisseur": "隔间鉴赏家",
    "Cultural Marxism": "文化马克思主义",
    "Currency Manipulator": "货币操纵器",
    "Current Employees": "当前员工",
    "Current Valuation": "当前估价",
    "Cursed Monkey's Paw ": "被诅咒的猴子的爪子",
    "Customer Courtier": "客户朝臣",
    "Customer Relationship Master": "客户关系主数据",
    "Cyclonic Brainstormer": "气旋式头脑风暴",
    "Dabbler": "小玩意",
    "Daddy Warbucks": "爸爸,战利品",
    "Daily Lunch Pick-Up": "每日午餐接送",
    "Day Trader": "日交易商",
    "Deadbeat Decision-Maker": "死气沉沉的决策者",
    "Death Squad Moneylenders": "死亡小组放债人",
    "Decentralized Crypto-Inboxes": "分散加密收件箱",
    "Decimator": "抽取器",
    "Declassified Coins": "解密硬币",
    "Deep State": "深州",
    "Deeper Mass Graves": "更深的集体墓穴",
    "Default Acquisitions Executives": "默认收购主管",
    "Defense Lobbyists": "国防游说者",
    "Definitely Too Many": "肯定太多了",
    "Departmental Insolvency": "部门破产",
    "Destiny Manifested": "命运显现",
    "Destroyer of Worlds": "世界毁灭者",
    "Detailed Spreadsheets": "详细电子表格",
    "Devil-Possessed Fingers": "恶魔附身的手指",
    "Did you say, 'Officer,I am not resisting you ? '": "你说了吗,警官,我没有反抗你？",
    "Digital Storyteller": "数字说书人",
    "Direct Lines to HR": "直接到HR",
    "Dirt-Covered Coins": "沾满灰尘的硬币",
    "Dirty Coins": "肮脏的硬币",
    "Disaster Price-Gouging": "灾难价格挖掘",
    "Disaster Reliever": "救灾",
    "Disciplinary Pay Cuts": "纪律性减薪",
    "Disciplined Debt Collectors": "纪律严明的收债人",
    "Discount For Acquisition Workers": "收购工人折扣",
    "Discount Leads": "折扣销售线索",
    "Disruptor": "破坏者",
    "Diverse Investments": "多样化投资",
    "Diversified": "多样化",
    "Dividend Destroyer": "股息驱逐舰",
    "Divine Mandates": "神圣的使命",
    "Divorce Papers": "离婚文件",
    "Dollars Per Hour": "每小时美元",
    "Dollars Per Minute": "每分钟美元",
    "Dollars Per Second": "每秒美元",
    "Domino Champ": "多米诺冠军",
    "Donated Coins": "捐赠的硬币",
    "Door-to-Door Charlatan": "挨家挨户的江湖骗子",
    "Doubled Down": "双下",
    "Downtrodden Workhorse": "被踩下的工作马",
    "DPS Multiplier Bonus": "DPS乘数奖金",
    "Draconian Brand Compliance": "严格的品牌合规性",
    "Dry Powdered": "干粉",
    "Dubious Investment Firms": "可疑投资公司",
    "Dulled Pain Receptors": "钝痛受体",
    "Duration Per Windfall": "每次意外收获的持续时间",
    "Dusty Coins": "尘土的硬币",
    "Duty-Free": "免税",
    "Dynamic Problem Solver": "动态问题解决方案",
    "Dystopian Imperial Cartel": "反乌托邦帝国卡特尔",
    "Ear to Ear, Baby": "耳听八方,宝贝",
    "Earned from Research": "从研究中获得",
    "Earned While Away": "离开时赢得",
    "Earning Rate While Away": "外出时的收益率",
    "Efficient Stratcom": "高效战略司令部",
    "Eight Hours Rest": "八小时休息",
    "Elder Statesman": "老政治家",
    "Elected Official": "当选官员",
    "Elephant Hunter": "猎象人",
    "Email Away Unlocked": "电子邮件已解除锁定",
    "Email Benefits Transfer Card": "电子邮件福利转移卡",
    "Email Chance Multiplier": "电子邮件机会乘数",
    "Email Freshness Timer": "电子邮件新鲜度计时器",
    "Email Text Bonus Multiplier": "电子邮件文本奖励乘数",
    "Emails Answered": "已回复电子邮件",
    "Emails Answered (All Businesses)": "回复的电子邮件（所有业务）",
    "Emergency Prepared": "应急准备",
    "Employee Discount": "员工折扣",
    "Employee of the Month": "当月员工",
    "Employee Types Available": "可用员工类型",
    "Employee Types Employed": "雇用的员工类型",
    "Employee-Wide Modifier": "员工范围修改器",
    "Employees Employed": "雇佣员工",
    "Employees Who Couldn't Hack it": "无法破解的员工",
    "Enhanced Interrogations": "强化审讯",
    "Entrenched Lobbyists": "根深蒂固的说客",
    "Esoteric Monoliths": "深奥的巨石",
    "Esprit De Corporate": "企业精神",
    "Established Corporation": "成立公司",
    "Eternal Recurrence": "永恒的重现",
    "Ethereal Sleeplessness": "空灵的失眠",
    "Even More of 'Em ": "甚至更多'em",
    "Ever Vigilant": "时刻保持警惕",
    "Every war but class war.": "每一场战争,除了阶级战争。",
    "Everything is a Priority": "一切都是优先考虑的",
    "Everything Must Go": "一切都必须走",
    "Everything's Coming Up Milhouse ": "每件事都会发生在米尔豪斯",
    "Evil Disembodied Fingers": "邪恶的食指",
    "Executive Assistants": "行政助理",
    "Executive Disgust": "行政厌恶",
    "Executive Financiers": "执行金融家",
    "Executive Lobbyists": "行政说客",
    "Exhilirating Rhetoric": "令人振奋的言辞",
    "Expired Emails Answered": "已回复过期电子邮件",
    "Exploitable Laborer": "可利用劳动者",
    "Extensive Nerve Damage": "广泛的神经损伤",
    "Extra Charisma": "超凡魅力",
    "Extra Email Addresses": "额外电子邮件地址",
    "Extra Phones": "额外的电话",
    "Extra-Broken Windows": "额外损坏的窗口",
    "Extra-Judicial Killings": "法外杀人",
    "Extrajudicial Prosecutors": "法外检察官",
    "Extremely Fine Print": "非常精细的打印",
    "Fabric Coins": "织物硬币",
    "Faceless Multinational Corporation": "无脸跨国公司",
    "False-Flag Operations": "错误标记操作",
    "Falsely Conscious": "错误意识",
    "Family Photos": "家庭照片",
    "Faster Software": "更快的软件",
    "Faster-than-Light Growth": "比光还快",
    "Fat Cat": "肥猫",
    "Fearless Stock Brokers": "无所畏惧的股票经纪人",
    "FEMA Internment Camps": "联邦应急管理局拘留营",
    "Fiercely Independent": "完全独立",
    "Filing for Chapter 50": "第50章的申请",
    "Financial Consultants": "财务顾问",
    "Finger Exercises": "手指练习",
    "Finger on the Button": "手指放在按钮上",
    "Finger on the Pulse": "手指在脉搏上",
    "Finger-Enhancing Drugs": "手指增强药物",
    "Fire Sale Afficionado": "消防销售关系",
    "Firehose Recipient": "消防水管接受者",
    "Firing Spree": "射击狂欢",
    "Firings in Name Only": "仅以名称触发",
    "First Responder": "第一响应者",
    "Flimsy Protective Railings": "脆弱的防护栏杆",
    "Fluoridated Water": "含氟水",
    "Flush with Cash": "现金充裕",
    "Focus Group Fanatic": "焦点小组狂热分子",
    "Folksy Servility": "民间的奴役",
    "For A Goddamn Percentage": "为了一个该死的百分比",
    "Forced HGH Injections": "强制hgh注射",
    "Forced Thimerosal Vaccines": "强制硫柳汞疫苗",
    "Fortune Favors the Fortunate": "幸运的人有福气",
    "Founder": "创始人",
    "Four-Dimensional Capitalist": "四维资本家",
    "Free Lunches": "免费午餐",
    "Free-Falling Minimum Wages": "自由下降的最低工资",
    "Fresh Emails Answered": "新邮件已回复",
    "Fresh New Startup": "新启动",
    "Fresh Suits": "新西装",
    "Fresh-Faced Candidate": "新面孔候选人",
    "From Your Keyboard to God's Ear": "从键盘到上帝的耳朵",
    "Frothier Markets": "泡沫市场",
    "Frozen Pensions": "冻结养老金",
    "Fruit-Flavored Coins": "水果味硬币",
    "Full Global Conquest": "全面的全球征服",
    "Full Sea Drainage": "全排水",
    "Full-Body Delousing": "全身去毛",
    "Full-Stack": "全栈",
    "Fully Legal Extortion": "完全合法的敲诈",
    "Fully Lucid Nightmares": "完全清醒的噩梦",
    "Fully Primed Pumps": "完全灌注泵",
    "Fully Qualified Leader": "完全合格的领导",
    "Fun Boss": "快乐老板",
    "Functionally Literate": "功能性识字",
    "Furious Subtext": "激烈的潜台词",
    "Fuzzier Math": "模糊数学",
    "G.A.O.T.U.": "G.A.O.T.U.",
    "Game Changer": "游戏改变者",
    "Gaseous Coins": "气态硬币",
    "Generational Debts": "世代债务",
    "Gently-Used Ear Plugs": "小心使用耳塞",
    "Giver of 110%": "给予者110%",
    "Glamorous Glennis": "迷人的格伦尼斯",
    "Globalizer": "全球化者",
    "Gold Coins": "金币",
    "Golden Parachutes": "金色降落伞",
    "Good Neighbor": "好邻居",
    "Good Quarterly Numbers": "良好的季度数字",
    "Government Grants": "政府补助",
    "Gratuitous Nepotism": "无缘无故的裙带关系",
    "Gravimetric Revenue Displacement": "重力收入位移",
    "Greasier Elbows": "更油腻的肘部",
    "Greedy Attorneys": "贪婪的律师",
    "Greenfield Territorialist": "格林菲尔德地区主义者",
    "Gritty Perseverance": "坚韧不拔的毅力",
    "Growth Hacked": "成长黑客",
    "Growth-Oriented": "面向增长",
    "Hands-Off": "放手",
    "Hands-On": "动手",
    "Harbinger of Trends": "趋势预兆",
    "Hard-Earned": "辛苦挣来的",
    "Haven't Heard Back...": "没有回音…",
    "Haver of Bandwidth": "带宽拥有者",
    "Hawthorne Effective": "霍桑有效",
    "Hear ye, the doctor has seen Nautulius.": "听我说,医生看到了鹦鹉螺。",
    "Highest Possible Roller": "可能的最高滚筒",
    "Highest-Strung": "最高串",
    "Hiring Spree": "雇佣狂欢",
    "Historic Institution": "历史机构",
    "Hoarder": "囤积者",
    "Hockey Stick Growth": "曲棍球棒成长",
    "Homeland Eradicator of Local Militants": "当地激进分子的国土铲除者",
    "Hostile Architecture": "敌对建筑",
    "How's That Boot Taste?": "靴子的味道怎么样？",
    "Huge Chattery Teeth": "巨大的牙齿颤动",
    "I Am the Bread of Life": "我是生命的面包",
    "I Declare... Bankruptcy!": "我宣布…破产！",
    "I Need it Yesterday": "我昨天需要它",
    "Idle Bonus Cash Earned": "获得的闲置奖金现金",
    "Idle Bonus Multiplier": "闲置奖金乘数",
    "Idle Bonus Rate": "闲置奖金率",
    "If a man's not a success, he's got no one to blame but himself.": "如果一个人不成功,除了他自己,没有人可以责怪他。",
    "Imperial Lord of Leads": "帝国领主",
    "Imperialist Moneylenders": "帝国主义放债人",
    "Imported Coins": "进口硬币",
    "In Search of Excellence": "追求卓越",
    "In the Black": "在黑暗中",
    "In The Trenches": "在战壕里",
    "In-House Accountants": "内部会计",
    "Inbox Maximum": "收件箱最大",
    "Incapable of Delegation": "无法授权",
    "Incomprehensible Jargon": "难以理解的行话",
    "Incubated": "孵化",
    "Indentured Servitude": "契约性地役权",
    "Independent Auditors": "独立审计师",
    "Industrialist": "实业家",
    "Infinite Self-Replication": "无限自我复制",
    "Infinitely Scalable": "无限可扩展",
    "Inheritance": "继承",
    "Inhuman Patience": "不人道的耐心",
    "Initial Patent Offering": "首次专利发行",
    "Initial Price": "初始价格",
    "Innovator": "创新者",
    "Insider Tips & Tricks": "内部提示和技巧",
    "Interest Rate (Per Minute)": "利率（每分钟）",
    "Intergenerational Labor": "代际劳动",
    "International Monetary Fun!": "国际货币乐趣！",
    "International Shell Companies": "国际壳牌公司",
    "Interpersonally Skilled": "人际技能",
    "Invasive Data-Mining": "入侵数据挖掘",
    "Inverted Salaries": "反向工资",
    "Investment Boost Bonus": "投资提振奖金",
    "Investment Time Boosted": "投资时间增加",
    "Investments Waiting to Cash Out": "等待兑现的投资",
    "It merely required no character.": "它只是不需要任何角色。",
    "It's Got a Lot of Numbers In It": "里面有很多数字",
    "It's Too Many Clicks": "点击次数太多",
    "Jahbulon's Dominion": "亚不容的统治",
    "Jingoistic Fervor": "沙文主义狂热",
    "Jolly Green Giant": "快乐的绿色巨人",
    "Junta Lobbyists": "军政府说客",
    "Just Catching Up": "只是追赶",
    "Just Checking In...": "刚签入…",
    "Just Enough Cooks": "只要有足够的厨师",
    "Kicked Back": "踢回",
    "La-li-lu-le-lo": "la li lu le lo（日语）",
    "Landed Gentry": "上岸贵族",
    "Last Time Active": "上次活动",
    "Late-Night Raids": "夜袭",
    "Law-Abiding Debt Collectors": "守法的收债人",
    "Le Epic Bacon Genius": "传奇培根天才",
    "Leave No Trace": "不留痕迹",
    "Legendary Conglomerate": "传奇集团",
    "Les Enfants Terrible": "孩子们太可怕了",
    "Less Bread, Fewer Roses": "少面包,少玫瑰",
    "Let's Take This Offline": "让我们脱机",
    "Lifer": "救生员",
    "Lightning Reflexes": "闪电反射",
    "Limited Merit Promotions": "有限价值促销",
    "Lingoism": "利己主义",
    "LinkedIn Luminary": "LinkedIn亮度",
    "Lisan al Gaib": "Lisan Al Gaib",
    "Liver Failure": "肝衰竭",
    "Loaned Coins": "借来的硬币",
    "Lobbyists Abroad": "国外的说客",
    "Local Establishment": "本地机构",
    "Locked Doors": "锁上的门",
    "Logorrheic Professionalism": "职业沉默症",
    "Long Investments (1 Hour or Over)": "长期投资（1小时或以上）",
    "Long Lists of Names": "长名单",
    "Look Upon My Works": "看看我的作品",
    "Loop Me In": "把我圈起来",
    "Looser Cannons": "更宽松的大炮",
    "Lord of the Round Table": "圆桌王",
    "Loss Leader": "损失领袖",
    "Lost Lemurian": "丢失的利莫里亚人",
    "Lots of Clicking": "大量点击",
    "Lots of Clicks, Maybe Too Many": "大量点击,可能太多",
    "Low-Functioning Sociopath": "功能低下的反社会者",
    "Low-Hanging Fruitarian": "低悬果树",
    "Low-Priced Plastic Goods": "低价塑料制品",
    "Luck Had Nothing to Do With It": "运气与此无关",
    "Lucky Rabbit's Foot": "幸运兔的脚",
    "Lucrative Charismata": "有利可图的魅力",
    "Lumpenproletariat": "流氓无产阶级",
    "Lunch Breaker": "午餐断路器",
    "Lunch with the Bosses": "与老板共进午餐",
    "Lyrical Away Messages": "抒情的留言",
    "Make Total Employ": "全员雇佣",
    "Making Some Big Changes": "做出一些重大改变",
    "Malthusian Trapper": "马尔萨斯捕猎者",
    "Man-Made Lakes of Cash": "人工现金湖",
    "Mandatory Engagement": "强制性约定",
    "Mandeville Pointed": "曼德维尔尖",
    "Manual Click Multiplier": "手动单击乘数",
    "Manual Click Percentage": "手动单击百分比",
    "Manual Clicks": "手动单击",
    "Manual Clicks (All Time)": "手动单击（一直）",
    "Market Cannibal": "市场食人",
    "Market Diviner": "市场预言家",
    "Market Penetrator": "市场渗透者",
    "Masonic Lobbyists": "共济会说客",
    "Mass Gun Confiscation": "大规模枪支没收",
    "Mass Incarceration": "大规模监禁",
    "Massive Layoffs": "大规模裁员",
    "Massive Layoffs Conducted (All Businesses)": "大规模裁员（所有业务）",
    "Massive Subsidies": "巨额补贴",
    "Master Delegator": "主授权人",
    "Master of Margins": "主页边距",
    "Master of the Pipeline": "管道主管",
    "Maverick": "特立独行",
    "Maximization of Throughput": "吞吐量最大化",
    "Maximized Leverager": "最大杠杆",
    "Maybe Too Many Now": "现在可能太多了",
    "Means-Tested Paychecks": "指经测试的工资支票",
    "Menacing Word Choice": "威胁词选择",
    "Mercenary Groups": "雇佣团体",
    "Meritocrat": "精英阶层",
    "Micromanager": "微经理",
    "Midnight Oil": "午夜油",
    "Militarized Checkpoints": "军事化检查站",
    "Militarized Lobbyists": "军事化的说客",
    "Militarized Market Surveyor": "军事化市场测量师",
    "Militarized Riot Control": "军事化暴乱控制",
    "Military Defense Attorneys ": "军事辩护律师",
    "Military-Issue Coins": "军事发行货币",
    "Minimally Viable": "最小可行",
    "Minimum Email Value": "最小电子邮件值",
    "Minimum Viable Personnel": "最低可行人员",
    "Missing Coins": "丢失的硬币",
    "Mission Accomplished": "任务完成",
    "Mission Civilisatrice": "文明使命",
    "Mission Critical": "关键任务",
    "MKUltra Sleeper Agents": "大脑控制实施者",
    "Moderate Lobbyists": "温和的说客",
    "Modifier": "修饰语",
    "Monetized": "货币化",
    "Monopolized Industries": "垄断行业",
    "Monstrous Work Ethic": "可怕的职业道德",
    "More Brow Sweat": "更多的眉头汗",
    "More gods, more masters.": "更多的神,更多的主人。",
    "More Hard Drives": "更多硬盘",
    "More of an Ideas Person": "更多的想法人",
    "More Vision": "更多的愿景",
    "Most Valuable Patent": "最有价值的专利",
    "Motivational Speeches": "励志演讲",
    "Motivational Work Conditions": "激励性工作条件",
    "Moving Fast & Breaking Everything": "快速移动并打破一切",
    "Mud-Caked Coins": "泥结硬币",
    "Multinational Moneylenders": "跨国放债人",
    "Must Have Missed a Decimal Point": "必须错过小数点",
    "My Name is My Name": "我的名字是我的名字",
    "Mysterious Fingers": "神秘的手指",
    "Naive Resilience": "幼稚的韧性",
    "Name Tags": "姓名标签",
    "Negative Severance": "负遣散费",
    "Neo-Feudal Lord": "新封建主",
    "Net Value": "净值",
    "New Achievements": "新成就",
    "New Policies": "新政策",
    "New Upgrades": "新升级",
    "New World Order": "新世界秩序",
    "Next Bankruptcy Multiplier": "下一个破产乘数",
    "No Limits to Growth": "没有增长限制",
    "No Rush": "不急",
    "No-Bid Contracts": "无投标合同",
    "Non-Competes": "非竞争",
    "Non-Stop Jackpot Winner": "不间断的头奖得主",
    "None More Bankrupt": "不再破产",
    "Not Here To Make Friends": "不是来交朋友的",
    "Nothing but Aces": "除了aces什么都没有",
    "Nothing on the Inside": "里面什么都没有",
    "Novikovian Time Manipulation": "时间操作机器",
    "Novus Ordo Seclorum": "时代新秩序（拉丁语）",
    "Now, Hold On, Mr. Potter": "等一下,波特先生",
    "Now, we can see a new world coming into view.": "现在,我们可以看到一个新的世界。",
    "Number Fudgings Occurred (All Businesses)": "发生的数字伪造（所有业务）",
    "Nutmeg is not the question.": "肉豆蔻不是问题。",
    "Occult Gatherings": "神秘聚会",
    "Odious Debt Collectors": "可恶的收债人",
    "Off-Shore Accountant": "离岸会计",
    "Off-Site Data Centers": "非现场数据中心",
    "Office Drone": "办公室无人驾驶飞机",
    "Officer Friendly": "军官友好",
    "Oily Coins": "油性硬币",
    "Old Money": "老钱",
    "Old Moneybags": "老钱袋",
    "Omnidimensional Marketing": "全方位营销",
    "On A Roll": "一溜烟",
    "On Call": "随叫随到",
    "On the Ball": "在舞会上",
    "Once when I was a child, I almost drowned. It's just like that feeling.": "有一次我还是个孩子的时候差点淹死。就像那种感觉。",
    "One Man Army": "一人军",
    "One World Unity Army": "一支世界统一军",
    "One-World Globalist": "一个世界的全球化者",
    "Open Borders": "开放边界",
    "Operation Rolling Layoffs": "运营滚动裁员",
    "OSHA Doesn't Need to Know": "OSHA不需要知道",
    "Otherwordly Rituals": "其他形式的仪式",
    "Out-of-Town Scabs": "出城的结痂",
    "Outgoing Emails Sent (All Businesses)": "发送的外发电子邮件（所有业务）",
    "Outright Lies": "彻头彻尾的谎言",
    "Overall Time Boosted (All Businesses)": "总体时间增长（所有业务）",
    "Overcooked Books": "煮过的书",
    "Overnight Conferences": "夜间会议",
    "Paid Protestors": "付费抗议者",
    "Paradigm Shifter": "范式转换器",
    "Paramilitary Debt Collectors": "准军事债务收集者",
    "Passive Observer": "被动观察者",
    "Patents Sold (All Businesses)": "出售专利（所有业务）",
    "Paternalistic Guilt": "家长式的负罪感",
    "Patriot Lobbyists": "爱国者说客",
    "Peacekeeper": "和平卫士",
    "Peak Efficiency": "峰值效率",
    "Penny Stock Pro": "专业便士股",
    "Permanent Isolation Cubicles": "永久隔离柜",
    "Perpetual Motion Machine": "永动机",
    "Personal Assistants": "私人助理",
    "Personal Responsibility": "个人责任",
    "Personal Touches": "个人接触",
    "Personnel Realignment Specialists": "人员调整专家",
    "Petrol-Soaked Coins": "浸透汽油的硬币",
    "Piggy Banker": "小猪银行家",
    "Pinker Slips": "Pinker Slips",
    "Pinkerton Reinforcements": "平克顿钢筋",
    "Pipeline Prophet": "管道先知",
    "Playful Threats": "顽皮的威胁",
    "Playing the Long Game": "玩长游戏",
    "Please Advise": "请告知",
    "Please Answer, Please": "请回答,请",
    "Please Respond ASAP": "请尽快回复",
    "Plenty to Go Around": "有很多可以去的地方",
    "Plutocrat": "财阀",
    "Pocket Politicians": "口袋政客",
    "Poisonous Coins": "有毒硬币",
    "Police Union Attorneys": "警察工会律师",
    "Police Union Lobbyists": "警察联盟说客",
    "Policies Accepted (All Businesses)": "接受的政策（所有业务）",
    "Policy Away Unlocked": "政策解除锁定",
    "Political Executions": "政治处决",
    "Postcards Home": "明信片主页",
    "Powder-Blackened Coins": "粉黑硬币",
    "Predatory Pricing": "掠夺性定价",
    "Premature": "早熟",
    "Presidential Lawyers": "总统律师",
    "Preternatually Wealthy": "非常富有",
    "Pretty Much All of 'Em": "几乎所有它们",
    "Pretty Much Just Lucky": "非常幸运",
    "Preventative Dental Extraction": "预防性拔牙",
    "Price": "价格",
    "Prime Deliverable": "主要可交付成果",
    "Primordial Global Conspiracy": "原始的全球阴谋",
    "Prison Lobbyists": "监狱说客",
    "Privatized Tax Collection": "私有化税收",
    "Privileged": "特权",
    "Proactive Leadership": "主动领导",
    "Procrastinator": "拖延者",
    "Productivity Mutations": "生产力突变",
    "Professional Liquidator": "专业清算人",
    "Professional Lobbyists": "专业说客",
    "Prolific Writer": "多产作家",
    "Prompt Responder": "提示响应程序",
    "Propaganda Machines": "宣传机器",
    "Protestant Work Ethic": "新教职业道德",
    "Public Defenders": "公共辩护人",
    "Public Shaming": "公开羞辱",
    "Pumping and Dumping": "泵送和倾倒",
    "Puppetmasters": "木偶大师",
    "Purge of the Weak": "清除弱者",
    "Putting Out Fires": "灭火",
    "Q. And Babies? A. And Babies.": "Q.还有婴儿？还有婴儿。",
    "Quantity": "数量",
    "Quantity Modifier": "数量修改器",
    "Quantum Computers": "量子计算机",
    "Quick Question...": "快速问题…",
    "Quickest Draw": "最快绘制",
    "Quincentennial Celebration": "五周年庆典",
    "Quitters Never Win": "放弃者永远不会赢",
    "R&D Time Boosted": "研发时间增加",
    "Radioactive Coins": "放射性硬币",
    "Rail Spike Coins": "铁轨钉硬币",
    "Ramen Profitable": "拉面盈利",
    "Randian Hero": "兰甸英雄",
    "Rapid Fire Speculator": "火速投机者",
    "Rapid Ideation": "快速构思",
    "Rapid Innovation": "快速创新",
    "Rapidly Pivoting": "快速旋转",
    "Reaching Out": "伸出手来",
    "Real Artists Ship": "真正的艺术家之船",
    "Realignment of Growth Opportunities": "调整增长机会",
    "Rearden Metallic": "Rearden金属漆",
    "Reasonably Suspicious": "合理怀疑",
    "Reassuring Leadership": "令人安心的领导",
    "Reduced Bonuses": "减少奖金",
    "Regular Emails": "常规电子邮件",
    "Reinforced Bank Vaults": "加固的银行金库",
    "Relentless Momentum": "无情的势头",
    "Relentless Rationalization": "无情的合理化",
    "Repurposed Coins": "重新调整用途的硬币",
    "Research Boost Bonus": "研究提振奖金",
    "Reshaper of Worlds": "重塑世界",
    "Resource Extraction": "资源提取",
    "Restless Defender": "不安的防御者",
    "Reverse Universal Heat Death": "反转宇宙热死亡",
    "Reverse Vacation Accrual": "反向假期累算",
    "Right-Wing Guerillas": "右翼游击队",
    "Righteous Debt Collectors": "正义的收债人",
    "Rightsizing!": "调整尺寸！",
    "Risk of Death": "死亡风险",
    "Risk Reduction": "风险降低",
    "Robber Baron": "强盗男爵",
    "Rockstar": "摇滚明星",
    "Roving Death Squads": "流动的死亡小队",
    "Rugged Individualism": "坚定的个人主义",
    "Running Fat": "跑胖",
    "Ruthless Streamliner": "无情的流线型",
    "Sacks with Dollar Signs": "带美元符号的袋子",
    "Sadistic Debt Collectors": "残暴的收债人",
    "Salaryman": "红衣主教",
    "Sales Hotshots": "销售热点",
    "Salted Coins": "咸硬币",
    "Save File Size": "保存文件大小",
    "Scalper": "黄牛",
    "Scorched Earth Policies": "焦土政策",
    "Screaming into the Void": "尖叫着进入空虚",
    "Screaming Sessions": "尖叫会议",
    "Secret Coins": "秘密硬币",
    "Secret Handshakes": "秘密握手",
    "Seed Accelerated": "种子加速",
    "Seed Money": "种子钱",
    "Self-Made Millionaire": "白手起家的百万富翁",
    "Self-Motivation": "自我激励",
    "Self-starter": "自我启动",
    "Sell Value": "出售价值",
    "Semi-Deified Tribute": "半神化贡品",
    "Semi-Qualified Stock Brokers": "半合格股票经纪人",
    "Senior Lobbyists": "高级说客",
    "Serial Entrepeneur": "连续输入",
    "Set It and Forget It": "设置并忘记它",
    "Seven-Leaf Clover": "七叶三叶草",
    "Seven-Million-Leaf Clover": "七百万片三叶草",
    "Several People Are Typing": "有几个人在打字",
    "Shadow Governments": "影子政府",
    "Shop Talk": "商店谈话",
    "Short Investment Bonus": "短期投资红利",
    "Short Investments (Under 1 Hour)": "短期投资（1小时以下）",
    "Shortened Vacations": "缩短假期",
    "Shorter Selling": "短线销售",
    "Sick and Tired of Winning": "厌倦了胜利",
    "Sick Capital Gains": "不良资本收益",
    "Silver Coins": "银币",
    "Simultaneous Acquisitions Allowed": "允许同时采集",
    "Simultaneous Investments Allowed": "允许同时投资",
    "Sincere Condolences": "诚挚的慰问",
    "Sisyphean Perseverance": "Sisyphean毅力",
    "Slanderous Accusations": "诽谤指控",
    "Slick Cowboy Stock Brokers": "狡猾的牛仔股票经纪人",
    "Slurry-Stained Coins": "泥浆染色硬币",
    "Smaller Cubicles": "小隔间",
    "Smart Words Replied": "智能单词已回复",
    "Snake Oil Sweet-Talker": "蛇油甜言蜜语",
    "Social Butterfly": "社交蝴蝶",
    "Some of Each": "每一个",
    "Soot-Covered Coins": "烟灰覆盖的硬币",
    "Sorry for the Delayed Response": "对延迟的响应感到抱歉",
    "Spam Disposal": "垃圾邮件处理",
    "Special Forces Philosophy": "特种部队哲学",
    "Speed Bonus": "速度奖金",
    "Speed Boost": "速度加速",
    "Sprawling Industrial Wasteland": "蔓延的工业荒地",
    "Stabs Tab Views": "插入选项卡视图",
    "Staring Dead-Eyed at the Inbox": "目不转睛地盯着收件箱",
    "Start Time (All Businesses)": "开始时间（所有业务）",
    "Start Time (This Business)": "开始时间（此业务）",
    "Sticky Coins": "粘硬币",
    "Stirring Corporate Pride": "令人振奋的企业自豪感",
    "Stress Level": "应激水平",
    "Stress Reduced Manually": "手动降低应力",
    "Stress Reduction Bonus": "减压奖金",
    "Stress Reduction Multiplier": "应力减少乘数",
    "Strike Gold": "罢工黄金",
    "Strip-Mall Moneylenders": "商业街放债人",
    "Stronger Brand Identity": "更强大的品牌标识",
    "Structural Adjustment Programs": "结构调整计划",
    "Struggling Insomniac": "努力失眠",
    "Struggling Sadsack": "苦苦挣扎的萨萨克",
    "Student Lobbyists": "学生游说者",
    "Student Protest Crackdowns": "学生抗议镇压",
    "Stuffy Office Lobbyists": "沉闷的办公室说客",
    "Sub-Prime Leader": "副总理",
    "Successful Investments": "成功投资",
    "Successful Investments (All Businesses)": "成功投资（所有业务）",
    "Sugary Coins": "含糖硬币",
    "Suicide Nets": "自杀网",
    "Superliminal Advertising": "超极限广告",
    "Superluminal Thinker": "超光速思想家",
    "Supernatural Magnate": "超自然巨头",
    "Supernatural Stock Brokers": "超自然的股票经纪人",
    "Supplemental Email Assistance Program": "补充电子邮件帮助计划",
    "Supplied & Demanded": "供应和需求",
    "Supranational Currency": "超国家货币",
    "Surge Pricing": "激增定价",
    "Surveillance Capitalist": "监视资本家",
    "Sweat Shops": "血汗商店",
    "Sweatier Equity": "流动资产",
    "Synergy-Related Adjustments": "协同相关调整",
    "Systematic Downsizing": "系统性裁员",
    "Tactical Flanking": "战术侧翼",
    "Tactical Trading": "战术交易",
    "Talk the Talk": "说说看",
    "Targeted Drone Firing": "目标无人机发射",
    "Targeted Surveillance": "目标监视",
    "Targeted Tax Cuts": "有针对性的减税",
    "Team-Building Exercises": "团队建设练习",
    "Telephone Terrorist": "电话恐怖分子",
    "Temporarily Embarrassed Millionaires": "暂时尴尬的百万富翁",
    "Tense & Silent Meetings": "紧张和沉默的会议",
    "Teracorn": "泰拉科恩",
    "Terminal Income Velocity": "终端收入速度",
    "Textile Coins": "纺织品硬币",
    "Thanks in Advance": "提前感谢",
    "The .0001%": "0001。",
    "The 0.0000001%": "0.0000001%",
    "The 1%": "1%",
    "The Absence of Alternatives": "缺乏备选方案",
    "The Affordable Emails Act": "负担得起的电子邮件法案",
    "The Ambitious Sales Model": "雄心勃勃的销售模式",
    "The Art of Acquisition": "获取的艺术",
    "The Bosses": "老板们",
    "The Challenger Sales Model": "挑战者销售模式",
    "The Chosen One": "选择的一个",
    "The Daemon Awakens": "守护进程唤醒",
    "The Death Special": "死亡特辑",
    "The Desire to Achieve": "实现愿望",
    "The Divine Right of Sales": "神圣的销售权",
    "The Elite Legal Team": "精英法律团队",
    "The Empire of Liberty": "自由帝国",
    "The Eye of Market Providence": "市场上帝之眼",
    "The Fifth Column": "第五列",
    "The Five Commas Club": "五大社区俱乐部",
    "The Fourth Woe": "第四个不幸",
    "The Freddie Mac Award for Ethics": "房地美伦理奖",
    "The Ghosts of Fallen Businesses": "堕落企业的幽灵",
    "The Giant Void": "巨大的空虚",
    "The Great Communicator": "伟大的沟通者",
    "The Great Motivator": "伟大的推动者",
    "The Holy Finger": "神圣的手指",
    "The Idle Class": "空闲类",
    "The Imperial Cult of the Goat": "皇帝对山羊的崇拜",
    "The Inbox of the Covenant": "契约的收件箱",
    "The Keynesian Dream": "凯恩斯主义梦想",
    "The Last Best Hope of Earth": "地球上最后的希望",
    "The Leanest Methodology": "最精简的方法",
    "The Lidless Eye": "无眼睑的眼睛",
    "The Little Red Book of Acquiring": "《小红皮书》",
    "The Man Behind the Curtain": "窗帘后面的那个人",
    "The Man Who Thought Different": "思想不同的人",
    "The Mark of the Beast": "野兽的印记",
    "The Means of Production": "生产手段",
    "The Militant Sales Model": "好战销售模式",
    "The Monopoly on Violence": "对暴力的垄断",
    "The Most Private of Equity": "最私人股本",
    "The Mostly Invisible Hand": "几乎看不见的手",
    "The Name on the Door": "门上的名字",
    "The Occult Sales Model": "神秘销售模式",
    "The Odic Sales Force": "ODIC销售团队",
    "The Office Gossip": "办公室八卦",
    "The Oligarchs": "寡头",
    "The People's Stick": "人民的棍子",
    "The Personable Sales Model": "个人销售模式",
    "The Poincaré Bankruptcy Theorem": "庞卡破产定理",
    "The Primordial Baʿal": "原始的Ba_al",
    "The Promise of Death": "死亡的承诺",
    "The Protectors of Our Industries": "我们行业的保护者",
    "The Reasonable Sales Model": "合理的销售模式",
    "The Reckless Sales Model": "不计后果的销售模式",
    "The Roarkian Ideal": "罗凯理想",
    "The Ruling Class": "统治阶级",
    "The Second Estate": "第二产业",
    "The Seven Commas Club": "七大社区俱乐部",
    "The Shoulders of Atlas": "阿特拉斯的肩膀",
    "The Spectre of Reorg": "瑞格的幽灵",
    "The Spoils of War": "战利品",
    "The Stargate Sales Model": "星门销售模式",
    "The Sum Total of the Universe": "宇宙的总和",
    "The Supreme Sales Model": "最高销售模式",
    "The Surplus Valuable": "剩余价值",
    "The Telecom Cowboy": "电信牛仔",
    "The Three Commas Club": "三个社区俱乐部",
    "The Wild Black Yonder ": "那边的野黑",
    "The World Banker": "世界银行家",
    "They have nothing to lose but their chains.": "除了锁链,他们没有什么可以失去的。",
    "Thin Blue Line": "细蓝线",
    "Thinly-Veiled Harassment": "薄纱骚扰",
    "This is a Business": "这是一项业务",
    "This Time, It's Personnel": "这一次它是人员",
    "Thought Leader": "思想领袖",
    "Threatening Diction": "威胁性措辞",
    "Time Bonus Rate (Hourly)": "时间奖金率（每小时）",
    "Time Dedicated to Investments": "投入投资的时间",
    "Time Dedicated to Investments (All Businesses)": "投入投资（所有业务）的时间",
    "Time Earning While Away": "外出时间收入",
    "Time Spent Idle": "空闲时间",
    "Time Spent Idle (All Businesses)": "闲置时间（所有业务）",
    "Time-Release Coins": "时间释放硬币",
    "Timeless Secret Cabal": "永恒的秘密阴谋集团",
    "Timesheet Authoritarianism": "时间表独裁主义",
    "Titan of Industry": "工业巨人",
    "Tobashi Schemer": "Tobashi Schemer",
    "Too Big to Fail": "太大而不能失败",
    "Top of a Better Funnel": "更好的漏斗顶部",
    "Total Financial Ouroboros": "总财务收益",
    "Total Mod to Cash Per Second": "每秒的总mod到cash",
    "Total Organizational Streamlining": "总体组织精简",
    "Total Storage": "总存储",
    "Total Windfalls": "总意外之财",
    "Total Windfalls (All Businesses)": "总收益（所有业务）",
    "Touching Base": "触摸底座",
    "Transparent Corruption": "透明腐败",
    "Trend Predestination": "趋势预定",
    "Trickle-Down Economics": "涓滴经济学",
    "trigger": "触发器",
    "Trilateral Commissioner": "三边专员",
    "Trimming the Fat": "修剪脂肪",
    "Trojan Horse Keyloggers": "特洛伊木马键盘记录器",
    "True Believer": "真正的信徒",
    "Two-Day Weekend": "两天周末",
    "Ubermensch": "乌伯门斯",
    "Ultra-Regressive Taxation": "超累进税",
    "Unachievable Metrics": "无法实现的指标",
    "Under New Management": "在新管理下",
    "Undocumented Coins": "未登记的硬币",
    "Unearned Self-Confidence": "自信心不足",
    "Unicorn": "独角兽",
    "Universal Acquisition": "通用采集",
    "Universal Acquittal": "普遍无罪判决",
    "Universal Basic Email": "通用基本电子邮件",
    "Universal Cash Bail": "环球现金保释",
    "Universal Flux": "通用通量",
    "Unlimited Vacation Days": "无限假期",
    "Unpaid Assistant": "无薪助理",
    "Unspeakable Lobbyists": "无法形容的说客",
    "Unstoppable Terrifying Luck": "势不可挡的可怕运气",
    "Untaxed Coins": "免税硬币",
    "Until the End of Time": "直到时间结束",
    "Upgrades Owned": "拥有升级",
    "Upgrades/Achievements Tab Views": "升级/成就选项卡视图",
    "Upper-Class Twit": "上层twit",
    "Upper-Level Lobbyists": "上层说客",
    "Urgent Email Bonus": "紧急电子邮件奖金",
    "Urgent Emails": "紧急电子邮件",
    "Urgent Emails Answered": "已回复紧急电子邮件",
    "Urgent Emails Answered (All Businesses)": "紧急电子邮件已回复（所有业务）",
    "Useless Degrees": "无用度",
    "User Storyteller": "用户说书人",
    "Value": "价值",
    "Value Bonus": "价值奖金",
    "Value Boost": "价值提升",
    "Value Mod": "价值模型",
    "Variable Capitalizer": "可变大写字母",
    "Vast Real Estate Acquisitions": "大规模房地产收购",
    "Venture Capital": "风险投资",
    "Venture Capitalist": "风险投资家",
    "Version": "版本",
    "Very Free Markets": "非常自由的市场",
    "Very Polite": "非常有礼貌",
    "Very Rude": "非常粗鲁",
    "Vicious Litigation": "恶意诉讼",
    "Vigilant Prodder": "警惕的推动者",
    "Virulent Feminism": "恶毒的女权主义",
    "Volunteer Lobbyists": "志愿游说者",
    "Voter Suppression": "选民抑制",
    "Water-Logged Coins": "积水硬币",
    "Wealthy Patrons": "富有的赞助人",
    "Well-Chopped Stocks": "切碎的股票",
    "Western Values": "西方价值观",
    "White Coins": "白色硬币",
    "White Shoes": "白鞋子",
    "Whiter Phosphorous": "白色磷",
    "Why We Fire": "我们为什么要开火",
    "Yacht Lobbyists": "游艇游说者",
    'Choke Their Rivers With Our Bankruptcies':'我们的破产扼杀了他们的河流',
    'Churning Out Innovation':'推动创新',
    'CIA-Sponsored Coups':'支持政变',
    'Circle Back':'循环回流',
    'Clearer Expectations':'清晰的期望',
    'Click Mod':'点击模块',
    'Clicks':'点击',
    'Client States':'附庸国',
    'Closed-Door Meetings':'闭门会议',
    'Coal-Dusted Coins':'煤粉硬币',
    'Collateral Damage':'附带损害',
    'Colonial Hegemony':'殖民霸权',
    'Colonial Sovereignty':'殖民主权',
    'Committed Crapshooter':'监狱杀手',
    'Community Policing':'社区治安',
    'Company Cultural Hegemony':'企业文化霸权',
    'Company Man':'公司职员',
    'Company Scrip':'公司票据',
    'Complete Deregulation':'撤销管制',
    'Completionist':'担保人',
    'Complimentary Amphetamines':'免费安非他命',
    'Comprehensive Outsourcing':'综合外包',
    'Compulsory Sedation':'强制性镇静',
    'Congenial Encouragement':'相投鼓励',
    'Content Creator':'内容创建者',
    'Cursed Monkey\'s Paw':'被诅咒的猴子爪子',
    'Did you say, \'Officer, I am not resisting you?\'':'你说过吗，“官员，我不是在拒绝你？”',
    'Even More of \'Em':'甚至更多的是：嗯..',
    'Everything\'s Coming Up Milhouse':'一切都是米尔豪斯的主意',



    //.3.待归类长句
    'A million dollars isn\'t cool. You know what\'s cool? A billion dollars.': '一百万美元并不酷。你知道什么才是酷吗？ 十亿美元。',
    'And So It Goes...': '如此这般……',
    'Any Update Here?': '有什么更新？',
    'Are You Getting These?': '你收到了吗？',
    'Benny, Bring Me Everyone': '本尼，给我带来每个人',
    'Can I Speak to the Manager?': '我可以和经理谈谈吗？',
    'Who Cares?': '谁在乎？',


    
    '<p>The ambitious <b>Middle Manager</b> is loyal to your business, striving each day to dominate your lower employees, lest they wither from a lack of motivating leadership.</p><p>Good old-fashioned common sense is their bread and butter, and they always know when it\'s time to tighten belts, roll up sleeves, and do less with more.</p>': '<p>雄心勃勃的<b>中层管理者</b>忠于你的事业，每天都努力主宰你的下级员工，以免他们因缺乏激励性的领导而枯萎。</p><p>优良传统是他们的面包和黄油，他们总是知道什么时候该系紧皮带，卷起袖子，少用多干。</p>',

    '<p>The brave <b>Privatized Cop</b> is the defender of your business, decked out in riot gear and gas masks as the last line of defense between bricks and your windows.</p><p>Armed and ready to protect and serve, they patrol your employees\' neighborhoods, upholding a fraternal code of ethics that ensures they only open fire when unnerved.</p>': '<p>勇敢的<b>内部安全人员</b>是企业的捍卫者，穿着防暴装备和防毒面具，是砖块和窗户之间的最后防线。</p><p>他们全副武装，随时准备保护和服务员工，在员工的社区巡逻，维护兄弟道德准则，确保员工只有在失去信心时才开火。</p>',

    '<p>The burgeoning <b>Client State</b> provides the life-blood of your business, supplying labor and resources at prices your own borders could never match.</p><p>There may be death squads in power, but that\'s the price you have to pay for a business-friendly environment that doesn\'t frown upon the execution of political agitators</p>': '<p>新兴的<b>客户端状态</b>为您的企业提供生命之源，以您自己的边界无法比拟的价格提供劳动力和资源。</p><p>也许有死亡小队在掌权，但这是你必须为一个商业友好的环境付出的代价，而这个环境并不反对政治鼓动者的执行。</p>',

    '<p>The confident <b>Sales Hotshot</b> is the engine of your business, bringing your valuable product(s) to your cash-laden customer(s), whether they want them or not.</p><p>Knee-deep in the pipeline and eyes locked on the quarterly numbers, they know that your business is dog-eat-dog, and dogs just don\'t live that long.</p>': '<p>自信的<b>销售热点</b>是您业务的引擎，无论您的客户是否需要，都可以将您的贵重产品带给他们。</p><p>膝盖深的管道和眼睛紧盯着季度数据，他们知道你的业务是狗吃狗，而狗只是不活那么久。<p>',

    '<p>The dignified <b>Pocket Politician</b> allows your business to thrive unburdened by Byzantine regulations, which would otherwise choke the life from it like a clumsy child in a textile mill.</p><p>Moderate and charismatic, they work hard for their constituents, ensuring with every vote that the most basic of needs is met: regular GDP growth.</p>': '<p>庄重的<b>袖珍政治家</b>让您的企业在不受拜占庭法规约束的情况下蓬勃发展，否则，拜占庭法规会像纺织厂里笨拙的孩子一样扼杀您的生活。</p><p>温和而富有魅力，他们为选民努力工作，确保每一次投票都能满足最基本的需求：正常的GDP增长。</p>',

    '<p>The humble <b>Intern</b> forms the backbone of any savvy business, paid in experience and eager to please as they pad their resumes in hopes of a better tomorrow.</p><p>With the exploitable pliability of youth glistening in their eyes, they scurry through the hallowed halls of your business, wearing multiple hats and incurring minimal expenses.</p>': '<p>谦卑的<b>实习医生</b>形成任何精明企业的支柱，付费经验和渴望满足，因为他们在写简历时希望有一个更好的明天。</p><p>年轻人的可利用的柔韧性在他们的眼睛里闪闪发光，他们匆匆穿过神圣的大厅，戴着多顶帽子，花费最少。</p>',

    '<p>The mysterious <b>Shadow Government</b> is the secret benefactor of your business, encouraging social discord and diminishing cultures as they please.</p><p>While not all believe they exist, true leaders such as yourself know that a once-great populace disarmed and hamstrung by political correctness is ripe for exploitation.</p>': '<p>神秘的<b>影子政府</b>是您企业的秘密恩人，鼓励社会不和谐，减少文化，只要他们愿意。</p><p>虽然并非所有人都相信他们的存在，但真正的领袖，如你自己，知道一个曾经伟大的民众，由于政治正确性而被解除武装并受到阻碍，已经成熟，可以被剥削。</p>',

    '<p>The noble <b>Blue Blood</b> is the soul of your business, investing in your continued growth, filling your boardrooms, and concentrating the wealth you create.</p><p>Self-made and determined, they watch for your ticker symbol as the markets climb, a sense of benevolent pride pouring over them as the dividends trickle down.</p>': '<p>豪气的<b>蓝血投资人</b>是您企业的灵魂，投资于您的持续增长，充实您的董事会会议室，集中您创造的财富。</p><p>他们自制并坚定，在市场攀升时，他们会注意到你的股票代码，当股息逐渐减少时，一种仁慈的自豪感倾泻在他们身上。</p>',

    '<p>The omniscient <b>Puppetmaster</b> is the primordial lizard-brain of your business, unspeakably powerful, hailing from a time beyond memory.</p><p>They may look and sound like any of us, but they travel in elite circles: tycoons and magnates, dignitaries and politicians, all gathered in hoods and masks to perform unspeakable horrors in the hidden basements of pizza parlors.</p>': '<p>无所不知的<b>木偶大师</b>是你事业中最原始的蜥蜴大脑，其强大无比，来自一个超越记忆的时代。</p><p>他们可能看起来和听起来像我们中的任何一个人，但他们在精英圈中旅行：大亨和大亨、高官和政治家，都聚集在头巾和面具中，在比萨店的隐藏地下室里表演难以形容的恐怖表演。</p>',

    '<p>The solemn <b>Wage Slave</b> is essential to the success of any growing business, dedicated to their work and trapped in an unbreakable cycle of poverty and obligation.</p><p>Through long nights and lonely weekends, they drag their ragged claws through offices and factory floors, each day hoping to be blessed with a coveted merit increase.</p>': '<p>严谨的<b>工资奴隶</b>对于任何不断发展的企业的成功都是至关重要的，他们致力于自己的工作，陷入了贫困和义务的牢不可破的循环中。</p><p>在漫长的夜晚和孤独的周末，他们把破烂的爪子伸进办公室和工厂的地板，每天都希望得到一份令人垂涎的功绩提升。</p>',

    '<p>The valorous <b>Mercenary Group</b> protects the interests of your business abroad, burning villages and salting the earth anywhere a government begins to lean left.</p><p>Stalwart and ready to just follow orders, they move from city to city, drone\'s-eye-view overhead, guns trained on the nearest target as they wait for the order to liberate.</p>': '<p>勇敢的<b>雇佣军集团</b>保护您在国外的业务利益，在政府左倾的任何地方焚烧村庄和盐渍土地。</p><p>他们坚定不移，随时准备服从命令，从一个城市到另一个城市，头顶上无人驾驶飞机的视野，在等待命令释放的同时对最近的目标进行枪械训练。<p>',

    '<p>The wise <b>C-Level</b> is the conductor of your business, always thinking of innovative and inspiring ways to appear to meet shareholder expectations or inflate valuations.</p><p>With a keen eye and a strict sense of discipline, they approach each new day as a chance to trim the fat and bring value to their investors.</p>': '<p>聪明的<b>C水平者</b>是您的业务的领导者，始终考虑创新和鼓舞人心的方式，以满足股东的期望或提高估值。</p><p>凭借敏锐的眼光和严格的纪律意识，他们每天都将新的一天视为一个削减脂肪并为投资者带来价值的机会。<p>',





    //1.2.成就
    'A City Upon a Hill':                       '山巅之城',
    'A Clear-Eyed Realist':                     '慧眼智者',
    'A Deal with the Devil':                    '与魔共舞',
    'A Few Extra Fingers':                      '额外控制',
    'A Shining Trapezohedron':                  '闪亮梯形',
    'A Silver Spoon':                           '银色茶匙',
    'Absentee Landlordism':                     '采邑领主',
    'Additional Buses':                         '附赠公交',
    'Administrative Dirty-Work':                '政治黑幕',
    'Aerospace Tech Group':                     '航天科工',
    'Aggressive Debt Collection':               '债务追索',
    'Aggressive Debt Collectors':               '专业追债',
    'All Accounts Deleted':                     '清除账户',
    'All-White Juries':                         '公平审判',
    'Amateur Debt Collectors':                  '业余追债',
    'Ambulance Chasers':                        '紧急救助',
    'Ancient Lobbyists':                        '古风说客',
    'Anthracite Coins':                         '亮煤货币',
    'Anti-Homeless Measures':                   '安民措施',
    'Anti-Union Literature':                    '革命手册',
    'Anxiety Medication':                       '焦虑药物',
    'Arbitrary Finger-Pointing':                '唯心指示',
    'Armed Militia Conscription':               '兵役法案',
    'Armed Rebel Groups':                       '武装叛军',
    'Army Surplus Gear':                        '备用军资',
    'Aspirational Loyalty':                     '忠诚伟志',
    'Attack Ads':                               '抨击广告',
    'Attorneys on Retainer':                    '授信讼师',
    'Automated Firing Algorithms':              '自动枪火',
    'Banana Coins':                             '香蕉货币',
    'Bane Capital':                             '灰色资本',
    'Baphometic Hypnotism':                     '宗教催眠',
    'Base Earnings':                            '基础收入',
    'Baseless Optimism':                        '盲目乐观',
    'Bathroom Panopticon':                      '单间浴室',
    'Bihourly Safety Meetings':                 '定期会晤',
    'Black Helicopters':                        '直升战机',
    'Black Site Debt Collectors':               '黑市追债',
    'Blackened Coins':                          '敦化货币',
    'Blood-Speckled Coins':                     '血斑货币',
    'Blood-Stained Coins':                      '血污货币',
    'Boardroom Lobbyists':                      '私房说客',
    'Bomb-Scorched Coins':                      '弹焦货币',
    'Bootstraps':                               '自力更生',
    'Borrowed Coins':                           '虚拟货币',
    'Bottle-Cap Coins':                         '瓶盖货币',
    'Boundless Advertising':                    '无边广告',
    'Boy\'s Club Comraderie':                   '光腚友情',
    'Brazen & Reckless Fraud':                  '无耻欺诈',
    'Budget Reductions':                        '削减预算',
    'Bullet-Riddled Coins':                     '弹孔货币',
    'Bullpen Lobbyists':                        '社交说客',
    'Bureaucratic Law Clerks':                  '官僚书记',
    'Bureaucratic Moneylenders':                '官商代理',
    'Burnt Coins':                              '燃烧货币',
    'Business Cards':                           '商业名片',
    'Business Precognition':                    '商业预感',
    'Campaign Contributions':                   '竞选献金',
    'Cash Bail Moneylenders':                   '保释代理',
    'Casual Fridays':                           '周五便装',
    'Casual Wage Discrimination':               '薪资歧视',
    'Casus Belli':                              '宣战理由',
    'Catastrophic Bailouts':                    '灾难救援',
    'Catastrophic Health Plans':                '救灾组织',
    'Centenarian Retirement':                   '百岁退休',
    'Chalky Coins':                             '白垩货币',
    'Champion of the Process':                  '工艺大师',
    'Chance of Windfall':                       '意外收获',
    'Chance to Receive Urgent Emails':          '提示机会',
    'Change Agent':                             '更换代理',
    'Chasing Returns':                          '追踪回报',
    'Chat Away Unlocked':                       '封锁回音',
    'Chat Messages':                            '聊天信息',
    'Chats Completed (All Businesses)':         '协商完成',
    'Cheap Hack Lawyers':                       '黑客律师',
    'Chem Trails':                              '化学痕迹',
    'Chemical-Burned Coins':                    '化工货币',
    'Chocolate Coins':                          '可可货币',

    _SHOWN_: function () {
        console.log(this._OTHER_);
        let
            $cni /*词汇数组*/ = arguments[0] || this._OTHER_,
            $str /*词汇字串*/ = document.createElement('div');
        $str = '汉化-待译（阳光汉化组）：\n\n';
        //整理元素
        for (let i = 0; i < $cni.length; i++) {
            $str += ('/*' + i + '*/ "' + $cni[i] + '": "",\n');
        }
        $str += '\n\n刷新可继续游戏；愿支持汉化请联系QQ：505397145。';
        alert($str);
    },

};

//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
//2.采集新词

var cnItem = function () {

    //.1.传参是否非空字串
    if (!arguments[0]) return;

    //.2.检验传参是否对象
    let text = arguments[0],
        s = '';
    if (typeof (text) != "string")
        return text;
    else
        s = arguments[0].charCodeAt();

    //.3.检验传参是否英文
    if (
        s < 'A' || (s > 'Z' && s < 'a') || (s > 'z')

    ) return text;

    //.4.检验字典是否可存
    if (!cnItems._OTHER_) cnItems._OTHER_ = [];

    //.5.遍历尝试匹配
    for (let i in cnItems) {
        //.5.1.字典已有词汇或译文、且译文不为空，则返回译文
        if (
            text == i || text == cnItems[i] &&
            cnItems[i] != ''
        )
            return cnItems[i];
    }

    //.6.遍历生词表是否收录
    for (
        let i = 0; i < cnItems._OTHER_.length; i++
    ) {
        //.6.1.已收录则直接返回
        if (text == cnItems._OTHER_[i])
            return text;
    }

    //.7.未收录则保存
    cnItems._OTHER_.push(text);
    cnItems._OTHER_.sort(
        function (a, b) {
            return a.localeCompare(b)
        }
    );

    /*
        //开启生词打印
        //console.log(
            '有需要汉化的英文：', text
        );
    */

    //.8.返回生词字串
    return text;
};
